from opcoes.db_migrate import (
    ColumnDef,
    ConstraintDef,
    IndexDef,
    TableBlueprint,
    _build_column_sql,
    _build_create_table_sql,
    _index_sql_for_target,
    _rewrite_schema_refs,
)


def test_rewrite_schema_refs_updates_quoted_and_unquoted_references() -> None:
    sql = (
        'CREATE INDEX idx_test ON admin.positions USING btree (ticker); '
        'SELECT nextval(\'admin.positions_id_seq\'::regclass), '
        '"admin".positions'
    )
    rewritten = _rewrite_schema_refs(
        sql,
        source_schema="admin",
        target_schema="destino",
    )
    assert "admin.positions" not in rewritten
    assert "admin.positions_id_seq" not in rewritten
    assert '"admin".positions' not in rewritten
    assert "destino.positions" in rewritten
    assert "destino.positions_id_seq" in rewritten
    assert '"destino".positions' in rewritten


def test_build_column_sql_preserves_identity_and_schema_aware_defaults() -> None:
    identity = ColumnDef(
        name="id",
        type_sql="BIGINT",
        not_null=True,
        default_expr=None,
        identity_kind="d",
    )
    regular = ColumnDef(
        name="created_at",
        type_sql="TIMESTAMPTZ",
        not_null=False,
        default_expr="timezone('UTC'::text, now())",
        identity_kind="",
    )

    assert (
        _build_column_sql(identity, source_schema="admin", target_schema="admin")
        == '"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL'
    )
    assert (
        _build_column_sql(regular, source_schema="admin", target_schema="destino")
        == '"created_at" TIMESTAMPTZ DEFAULT timezone(\'UTC\'::text, now())'
    )


def test_build_create_table_sql_includes_constraints() -> None:
    blueprint = TableBlueprint(
        schema="admin",
        table="positions",
        columns=[
            ColumnDef(
                name="id",
                type_sql="BIGINT",
                not_null=True,
                default_expr=None,
                identity_kind="d",
            ),
            ColumnDef(
                name="ticker",
                type_sql="TEXT",
                not_null=True,
                default_expr=None,
                identity_kind="",
            ),
        ],
        constraints=[ConstraintDef(name="positions_pkey", definition="PRIMARY KEY (id)")],
        indexes=[],
    )

    sql = _build_create_table_sql(blueprint, target_schema="destino")
    assert 'CREATE TABLE IF NOT EXISTS "destino"."positions"' in sql
    assert 'CONSTRAINT "positions_pkey" PRIMARY KEY (id)' in sql


def test_index_sql_for_target_adds_if_not_exists_and_rewrites_schema() -> None:
    index = IndexDef(
        name="idx_positions_ticker",
        definition="CREATE INDEX idx_positions_ticker ON admin.positions USING btree (ticker)",
    )
    sql = _index_sql_for_target(
        index,
        source_schema="admin",
        target_schema="destino",
    )
    assert sql.startswith("CREATE INDEX IF NOT EXISTS idx_positions_ticker")
    assert " ON destino.positions " in sql
