from __future__ import annotations

from typing import Any


_AUDITED_TABLES = ("positions", "ledger")


def _table_exists(conn: Any, table_name: str) -> bool:
    row = conn.execute("SELECT to_regclass(?)", (table_name,)).fetchone()
    if row is None:
        return False
    if isinstance(row, dict):
        return next(iter(row.values()), None) is not None
    try:
        return row[0] is not None
    except (IndexError, KeyError, TypeError):
        return False


def ensure_change_history(conn: Any, *, commit: bool = False) -> None:
    """Instala o histórico append-only no schema ativo, sem alterar registros."""

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS record_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            source_table TEXT NOT NULL,
            source_id BIGINT NOT NULL,
            change_kind TEXT NOT NULL CHECK (change_kind IN ('UPDATE', 'DELETE')),
            actor TEXT NOT NULL DEFAULT 'system',
            reason TEXT,
            prior_values JSONB NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_record_history_source
        ON record_history (source_table, source_id, occurred_at DESC)
        """
    )
    conn.execute(
        """
        CREATE OR REPLACE FUNCTION record_history_capture_change()
        RETURNS trigger AS $$
        BEGIN
            INSERT INTO record_history (
                source_table, source_id, change_kind, actor, reason, prior_values
            )
            VALUES (
                TG_TABLE_NAME,
                OLD.id,
                TG_OP,
                COALESCE(NULLIF(current_setting('opcoes.audit_actor', true), ''), 'system'),
                NULLIF(current_setting('opcoes.audit_reason', true), ''),
                to_jsonb(OLD)
            );
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    conn.execute(
        """
        CREATE OR REPLACE FUNCTION record_history_reject_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'record_history é imutável; registre uma nova alteração.';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    conn.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_trigger
                WHERE tgname = 'record_history_immutable_trigger'
                  AND tgrelid = 'record_history'::regclass
            ) THEN
                CREATE TRIGGER record_history_immutable_trigger
                BEFORE UPDATE OR DELETE ON record_history
                FOR EACH ROW EXECUTE FUNCTION record_history_reject_mutation();
            END IF;
        END;
        $$
        """
    )

    for table_name in _AUDITED_TABLES:
        if not _table_exists(conn, table_name):
            continue
        trigger_name = f"record_history_{table_name}_trigger"
        conn.execute(
            f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_trigger
                    WHERE tgname = '{trigger_name}'
                      AND tgrelid = '{table_name}'::regclass
                ) THEN
                    CREATE TRIGGER {trigger_name}
                    BEFORE UPDATE OR DELETE ON {table_name}
                    FOR EACH ROW EXECUTE FUNCTION record_history_capture_change();
                END IF;
            END;
            $$
            """
        )
    if commit:
        conn.commit()


def install_change_history() -> None:
    """Instala o histórico no schema configurado, sem alterar registros ativos."""

    from .db import open_db

    conn = open_db()
    try:
        ensure_change_history(conn, commit=True)
    finally:
        conn.close()


def set_change_context(conn: Any, *, actor: str | None, reason: str | None) -> None:
    normalized_actor = (actor or "").strip() or "system"
    normalized_reason = (reason or "").strip()
    if len(normalized_actor) > 128:
        raise ValueError("Responsável pela alteração excede 128 caracteres.")
    if len(normalized_reason) > 1_000:
        raise ValueError("Motivo da alteração excede 1000 caracteres.")
    conn.execute(
        "SELECT set_config('opcoes.audit_actor', ?, true)",
        (normalized_actor,),
    )
    conn.execute(
        "SELECT set_config('opcoes.audit_reason', ?, true)",
        (normalized_reason,),
    )


def list_change_history(
    conn: Any,
    *,
    source_table: str,
    source_id: int,
) -> list[dict[str, Any]]:
    if source_table not in _AUDITED_TABLES:
        raise ValueError("Tabela de histórico não permitida.")
    rows = conn.execute(
        """
        SELECT id, occurred_at, source_table, source_id, change_kind, actor, reason, prior_values
        FROM record_history
        WHERE source_table = ? AND source_id = ?
        ORDER BY id ASC
        """,
        (source_table, int(source_id)),
    ).fetchall()
    return [dict(row) for row in rows]


__all__ = [
    "ensure_change_history",
    "install_change_history",
    "list_change_history",
    "set_change_context",
]
