from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

from .config import (
    get_postgres_schema,
)
from .db_health import resolve_postgres_target
from .utils import infer_option_type, parse_ptbr_number


class _PgResult:
    def __init__(
        self,
        rows: Optional[list[Mapping[str, Any]]] = None,
        *,
        rowcount: int = 0,
        lastrowid: Optional[int] = None,
    ) -> None:
        self._rows = list(rows or [])
        self.rowcount = int(rowcount or 0)
        self.lastrowid = lastrowid

    def fetchone(self):
        if not self._rows:
            return None
        return self._rows[0]

    def fetchall(self):
        return list(self._rows)


class _DbConn:
    def __init__(self, *, raw_conn: Any, pg_row_factory: Any = None) -> None:
        self.backend = "postgres"
        self._raw_conn = raw_conn
        self._pg_row_factory = pg_row_factory

    def execute(self, query: str, params: Sequence[object] = ()):
        query_pg = query.replace("%", "%%").replace("?", "%s")
        with self._raw_conn.cursor(row_factory=self._pg_row_factory) as cur:
            cur.execute(query_pg, tuple(params))
            rowcount = int(cur.rowcount or 0)
            if cur.description is None:
                return _PgResult([], rowcount=rowcount)
            rows = cur.fetchall()
            return _PgResult(rows, rowcount=rowcount)

    def executemany(self, query: str, params_seq: Sequence[Sequence[object]]) -> None:
        query_pg = query.replace("%", "%%").replace("?", "%s")
        with self._raw_conn.cursor() as cur:
            cur.executemany(query_pg, params_seq)

    def commit(self) -> None:
        self._raw_conn.commit()

    def close(self) -> None:
        self._raw_conn.close()


def _quote_ident(value: str) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def _connect_postgres() -> _DbConn:
    target, errors = resolve_postgres_target()
    if target is None:
        reasons = "; ".join(errors) if errors else "configuração ausente"
        raise RuntimeError(f"PostgreSQL não configurado: {reasons}")
    try:
        import psycopg
        from psycopg.rows import dict_row
    except Exception as exc:
        raise RuntimeError(
            "Driver psycopg não encontrado. Instale com: uv add psycopg[binary]"
        ) from exc

    schema = get_postgres_schema()
    raw_conn = psycopg.connect(target.dsn, row_factory=dict_row)
    with raw_conn.cursor() as cur:
        cur.execute(f"CREATE SCHEMA IF NOT EXISTS {_quote_ident(schema)}")
        cur.execute(f"SET search_path TO {_quote_ident(schema)}")
    conn = _DbConn(raw_conn=raw_conn, pg_row_factory=dict_row)
    _ensure_tables(conn)
    return conn


def _connect(db_path: Optional[Path] = None) -> _DbConn:
    if db_path is not None:
        raise RuntimeError(
            "SQLite legado removido: history não suporta mais db_path por arquivo."
        )
    return _connect_postgres()


def _table_exists(conn: _DbConn, table: str) -> bool:
    row = conn.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = ?
        LIMIT 1
        """,
        (table,),
    ).fetchone()
    return row is not None


def _ensure_tables(conn: _DbConn) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS ranking_entries (
            snapshot_date TEXT NOT NULL,
            category TEXT NOT NULL,
            ticker TEXT NOT NULL,
            underlying TEXT,
            option_type TEXT,
            vencimento TEXT,
            dias_uteis INTEGER,
            score_total DOUBLE PRECISION,
            best_bid DOUBLE PRECISION,
            best_ask DOUBLE PRECISION,
            preco_teorico DOUBLE PRECISION,
            ultimo DOUBLE PRECISION,
            vol_impl_perc DOUBLE PRECISION,
            iv_rank_180d DOUBLE PRECISION,
            underlying_price DOUBLE PRECISION,
            extras TEXT,
            PRIMARY KEY (snapshot_date, category, ticker)
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS ranking_runs (
            snapshot_date TEXT PRIMARY KEY,
            params TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS decisions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            snapshot_date TEXT NOT NULL,
            ticker TEXT NOT NULL,
            underlying TEXT,
            option_type TEXT,
            vencimento TEXT,
            dias_uteis INTEGER,
            strike DOUBLE PRECISION,
            best_bid DOUBLE PRECISION,
            best_ask DOUBLE PRECISION,
            ultimo DOUBLE PRECISION,
            preco_teorico DOUBLE PRECISION,
            score_total DOUBLE PRECISION,
            vol_impl_perc DOUBLE PRECISION,
            iv_rank_180d DOUBLE PRECISION,
            underlying_price DOUBLE PRECISION,
            underlying_price_date TEXT,
            raw_row TEXT,
            notes TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    conn.commit()


def _row_to_dict(row: Any) -> Dict[str, Any]:
    if row is None:
        return {}
    if isinstance(row, Mapping):
        return dict(row)
    try:
        return dict(row)
    except Exception:
        return {}


def _parse_float(value: Any) -> Optional[float]:
    parsed = parse_ptbr_number(value)
    if parsed is None:
        return None
    try:
        return float(parsed)
    except Exception:  # noqa: BLE001
        return None


def record_ranking_entries(
    snapshot_date: str,
    categories: Mapping[str, Sequence[Mapping[str, Any]]],
    params: Optional[Mapping[str, Any]] = None,
    *,
    db_path: Optional[Path] = None,
) -> None:
    """Grava listas de ranking (top/racional/loteria/teórica) por data."""

    conn = _connect(db_path)
    try:
        if params is not None:
            params_json = json.dumps(params, ensure_ascii=False)
            conn.execute(
                """
                INSERT INTO ranking_runs (snapshot_date, params)
                VALUES (?, ?)
                ON CONFLICT (snapshot_date) DO UPDATE SET
                    params = EXCLUDED.params
                """,
                (snapshot_date, params_json),
            )

        payload: List[Tuple] = []
        extra_keys = [
            "Status_Moneyness",
            "Status_Liquidez",
            "Status_2x",
            "Status_Remoto",
            "breakeven_price",
            "breakeven_dist_pct",
            "prob_itm_pct",
            "prob_itm_delta_pct",
            "prob_be_pct",
            "custo_pct",
            "extrinsic_value",
            "extrinsic_pct_spot",
            "spread_pct",
            "iv_hv_spread",
        ]

        for category, rows in categories.items():
            for r in rows:
                ticker = str(r.get("ticker") or "").strip().upper()
                if not ticker:
                    continue
                underlying = (r.get("underlying") or "").strip().upper() or None
                venc = (r.get("vencimento") or "").strip() or None
                dias_uteis = None
                try:
                    dias_uteis = int(r.get("dias_uteis")) if r.get("dias_uteis") is not None else None
                except Exception:
                    dias_uteis = None
                opt_type = (r.get("option_type") or infer_option_type(ticker) or "").upper() or None

                extras: Dict[str, Any] = {}
                for key in extra_keys:
                    val = r.get(key)
                    parsed = _parse_float(val)
                    extras[key] = parsed if parsed is not None else (val if val not in ("", None) else None)
                extras_clean = {k: v for k, v in extras.items() if v not in (None, "")}
                extras_json = json.dumps(extras_clean, ensure_ascii=False) if extras_clean else None

                payload.append(
                    (
                        snapshot_date,
                        category,
                        ticker,
                        underlying,
                        opt_type,
                        venc,
                        dias_uteis,
                        _parse_float(r.get("score_total")),
                        _parse_float(r.get("best_bid")),
                        _parse_float(r.get("best_ask")),
                        _parse_float(r.get("preco_teorico")),
                        _parse_float(r.get("ultimo")),
                        _parse_float(r.get("vol_impl_perc")),
                        _parse_float(r.get("iv_rank_180d")),
                        _parse_float(r.get("underlying_price")),
                        extras_json,
                    )
                )

        if payload:
            conn.executemany(
                """
                INSERT INTO ranking_entries (
                    snapshot_date, category, ticker, underlying, option_type,
                    vencimento, dias_uteis, score_total, best_bid, best_ask,
                    preco_teorico, ultimo, vol_impl_perc, iv_rank_180d,
                    underlying_price, extras
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT (snapshot_date, category, ticker) DO UPDATE SET
                    underlying = EXCLUDED.underlying,
                    option_type = EXCLUDED.option_type,
                    vencimento = EXCLUDED.vencimento,
                    dias_uteis = EXCLUDED.dias_uteis,
                    score_total = EXCLUDED.score_total,
                    best_bid = EXCLUDED.best_bid,
                    best_ask = EXCLUDED.best_ask,
                    preco_teorico = EXCLUDED.preco_teorico,
                    ultimo = EXCLUDED.ultimo,
                    vol_impl_perc = EXCLUDED.vol_impl_perc,
                    iv_rank_180d = EXCLUDED.iv_rank_180d,
                    underlying_price = EXCLUDED.underlying_price,
                    extras = EXCLUDED.extras
                """,
                payload,
            )
        conn.commit()
    finally:
        conn.close()


def record_decision(
    ticker: str,
    *,
    snapshot_date: Optional[str] = None,
    notes: Optional[str] = None,
    db_path: Optional[Path] = None,
) -> Optional[int]:
    """Grava a linha completa de um ticker do snapshot mais recente (ou de uma data)."""

    conn = _connect(db_path)
    try:
        if not _table_exists(conn, "option_snapshots"):
            return None

        normalized_ticker = ticker.strip().upper()
        if snapshot_date:
            row = conn.execute(
                "SELECT * FROM option_snapshots WHERE ticker = ? AND snapshot_date = ? LIMIT 1",
                (normalized_ticker, snapshot_date),
            ).fetchone()
        else:
            row = conn.execute(
                """
                SELECT *
                FROM option_snapshots
                WHERE ticker = ?
                ORDER BY snapshot_date DESC
                LIMIT 1
                """,
                (normalized_ticker,),
            ).fetchone()
        if not row:
            return None
        data = _row_to_dict(row)
        snap_date = data.get("snapshot_date")
        venc = data.get("vencimento")
        dias_uteis = None
        try:
            dias_uteis = int(data.get("dias_uteis")) if data.get("dias_uteis") is not None else None
        except Exception:
            dias_uteis = None

        payload = (
            snap_date,
            normalized_ticker,
            (data.get("underlying") or "").strip().upper() or None,
            (data.get("option_type") or infer_option_type(ticker) or "").upper() or None,
            venc,
            dias_uteis,
            _parse_float(data.get("strike")),
            _parse_float(data.get("best_bid")),
            _parse_float(data.get("best_ask")),
            _parse_float(data.get("ultimo")),
            _parse_float(data.get("preco_teorico")),
            _parse_float(data.get("score_total")),
            _parse_float(data.get("vol_impl_perc")),
            _parse_float(data.get("iv_rank_180d")),
            _parse_float(data.get("underlying_price")),
            data.get("underlying_price_date"),
            json.dumps(data, ensure_ascii=False),
            notes,
        )

        cur = conn.execute(
            """
            INSERT INTO decisions (
                snapshot_date, ticker, underlying, option_type, vencimento,
                dias_uteis, strike, best_bid, best_ask, ultimo, preco_teorico,
                score_total, vol_impl_perc, iv_rank_180d, underlying_price,
                underlying_price_date, raw_row, notes
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING id
            """,
            payload,
        )
        inserted = cur.fetchone()
        conn.commit()
        if inserted is None:
            return None
        if isinstance(inserted, Mapping):
            return int(inserted.get("id"))
        return int(inserted[0])
    finally:
        conn.close()


def list_decisions(*, limit: Optional[int] = None, db_path: Optional[Path] = None) -> List[Dict[str, Any]]:
    conn = _connect(db_path)
    try:
        if not _table_exists(conn, "decisions"):
            return []
        query = "SELECT * FROM decisions ORDER BY created_at DESC, id DESC"
        if limit is not None and limit > 0:
            query += " LIMIT ?"
            params: Tuple[Any, ...] = (limit,)
        else:
            params = ()
        rows = conn.execute(query, params).fetchall()
        return [_row_to_dict(r) for r in rows]
    finally:
        conn.close()


def cleanup_history(
    *,
    retention_days: int = 180,
    purge_snapshots: bool = False,
    today: Optional[dt.date] = None,
    db_path: Optional[Path] = None,
) -> Dict[str, int]:
    """Remove rankings (e opcionalmente snapshots) antigos ou vencidos."""

    today = today or dt.date.today()
    cutoff = today - dt.timedelta(days=max(retention_days, 0))
    cutoff_iso = cutoff.isoformat()
    removed: Dict[str, int] = {"ranking_entries": 0, "ranking_runs": 0, "option_snapshots": 0, "underlying_snapshots": 0}

    conn = _connect(db_path)
    try:
        if _table_exists(conn, "ranking_runs"):
            run_del = conn.execute("DELETE FROM ranking_runs WHERE snapshot_date < ?", (cutoff_iso,))
            removed["ranking_runs"] = int(run_del.rowcount or 0)

        if _table_exists(conn, "ranking_entries"):
            entry_del = conn.execute("DELETE FROM ranking_entries WHERE snapshot_date < ?", (cutoff_iso,))
            removed["ranking_entries"] = int(entry_del.rowcount or 0)

            rows = conn.execute(
                "SELECT snapshot_date, category, ticker, vencimento FROM ranking_entries WHERE vencimento IS NOT NULL"
            ).fetchall()
            to_delete: List[Tuple[str, str, str]] = []
            for r in rows:
                data = _row_to_dict(r)
                venc = str(data.get("vencimento") or "").strip()
                try:
                    venc_date = dt.datetime.strptime(venc, "%d/%m/%Y").date()
                except Exception:
                    continue
                if venc_date < today:
                    to_delete.append(
                        (
                            str(data.get("snapshot_date") or ""),
                            str(data.get("category") or ""),
                            str(data.get("ticker") or ""),
                        )
                    )
            if to_delete:
                conn.executemany(
                    """
                    DELETE FROM ranking_entries
                    WHERE snapshot_date = ? AND category = ? AND ticker = ?
                    """,
                    to_delete,
                )
                removed["ranking_entries"] += len(to_delete)

        if purge_snapshots:
            if _table_exists(conn, "option_snapshots"):
                snap_del = conn.execute(
                    "DELETE FROM option_snapshots WHERE snapshot_date < ?",
                    (cutoff_iso,),
                )
                removed["option_snapshots"] = int(snap_del.rowcount or 0)
            if _table_exists(conn, "underlying_snapshots"):
                und_del = conn.execute(
                    "DELETE FROM underlying_snapshots WHERE snapshot_date < ?",
                    (cutoff_iso,),
                )
                removed["underlying_snapshots"] = int(und_del.rowcount or 0)

            if _table_exists(conn, "option_snapshots"):
                rows = conn.execute(
                    "SELECT snapshot_date, ticker, vencimento FROM option_snapshots WHERE vencimento IS NOT NULL"
                ).fetchall()
                to_delete_snap: List[Tuple[str, str]] = []
                for r in rows:
                    data = _row_to_dict(r)
                    venc = str(data.get("vencimento") or "").strip()
                    try:
                        venc_date = dt.datetime.strptime(venc, "%d/%m/%Y").date()
                    except Exception:
                        continue
                    if venc_date < today:
                        to_delete_snap.append(
                            (
                                str(data.get("snapshot_date") or ""),
                                str(data.get("ticker") or ""),
                            )
                        )
                if to_delete_snap:
                    conn.executemany(
                        """
                        DELETE FROM option_snapshots
                        WHERE snapshot_date = ? AND ticker = ?
                        """,
                        to_delete_snap,
                    )
                    removed["option_snapshots"] += len(to_delete_snap)

        conn.commit()
        return removed
    finally:
        conn.close()


__all__ = [
    "record_ranking_entries",
    "record_decision",
    "list_decisions",
    "cleanup_history",
]
