from __future__ import annotations

import datetime as dt
import math
import re
from typing import Any, Mapping, Optional, Sequence

from .db import open_db
from .portfolio import list_positions
from .utils import infer_option_type


class HoldingValidationError(RuntimeError):
    def __init__(self, message: str, *, ticker: str | None = None) -> None:
        super().__init__(message)
        self.ticker = ticker


def _normalize_ticker(value: str | None) -> str:
    return (value or "").strip().upper()


def _looks_like_equity_ticker(value: str | None) -> bool:
    return re.fullmatch(r"[A-Z]{4}\d{1,2}", _normalize_ticker(value)) is not None


def _canonical_stock_ticker(*, ticker: str | None, underlying: str | None) -> str:
    normalized_ticker = _normalize_ticker(ticker)
    normalized_underlying = _normalize_ticker(underlying)
    if _looks_like_equity_ticker(normalized_underlying):
        return normalized_underlying
    return normalized_ticker


def _is_legacy_stock_position(pos: Mapping[str, Any]) -> bool:
    ticker = _normalize_ticker(pos.get("ticker"))
    if not ticker or infer_option_type(ticker) in {"CALL", "PUT"}:
        return False
    if (pos.get("side") or "").strip().lower() == "short":
        return False
    if (pos.get("status") or "").strip().lower() != "open":
        return False
    strategy_tag = (pos.get("strategy_tag") or "").strip().lower()
    if strategy_tag == "ranking":
        return False
    trade_type = (pos.get("trade_type") or "").strip().lower()
    underlying = _normalize_ticker(pos.get("underlying"))
    if strategy_tag == "estoque" or trade_type == "stock":
        return True
    if underlying and ticker == underlying:
        return True
    if _looks_like_equity_ticker(ticker) and not underlying:
        return True
    if _looks_like_equity_ticker(ticker) and _looks_like_equity_ticker(underlying):
        return True
    return False


def _is_reserved_call_position(pos: Mapping[str, Any]) -> bool:
    ticker = _normalize_ticker(pos.get("ticker"))
    underlying = _normalize_ticker(pos.get("underlying"))
    if not ticker or not underlying:
        return False
    if infer_option_type(ticker) != "CALL":
        return False
    if (pos.get("status") or "").strip().lower() != "open":
        return False
    if (pos.get("side") or "").strip().lower() != "short":
        return False
    return (pos.get("strategy_tag") or "").strip().lower() == "covered_call"


def _ensure_tables(conn: Any) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS equity_holdings (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticker TEXT NOT NULL,
                quantity INTEGER NOT NULL,
                avg_price DOUBLE PRECISION NOT NULL,
                notes TEXT,
                needs_review INTEGER DEFAULT 0,
                is_simulated INTEGER DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                UNIQUE (ticker, is_simulated)
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS equity_holding_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticker TEXT NOT NULL,
                event_date TEXT NOT NULL,
                event_type TEXT NOT NULL,
                qty_delta INTEGER NOT NULL,
                quantity_before INTEGER NOT NULL,
                quantity_after INTEGER NOT NULL,
                avg_price_before DOUBLE PRECISION,
                avg_price_after DOUBLE PRECISION,
                price_reference DOUBLE PRECISION,
                fees DOUBLE PRECISION NOT NULL DEFAULT 0,
                notes TEXT,
                related_position_id BIGINT,
                is_simulated INTEGER DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
            """
        )
        cur.execute(
            "ALTER TABLE equity_holding_events "
            "ADD COLUMN IF NOT EXISTS fees DOUBLE PRECISION NOT NULL DEFAULT 0"
        )
        cur.execute(
            "CREATE INDEX IF NOT EXISTS idx_equity_holdings_ticker_mode ON equity_holdings (ticker, is_simulated)"
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_equity_holding_events_ticker_mode_date
            ON equity_holding_events (ticker, is_simulated, event_date DESC, id DESC)
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_equity_holding_events_position
            ON equity_holding_events (related_position_id)
            """
        )


def _resolve_conn(conn: Any | None) -> tuple[Any, bool]:
    if conn is not None:
        _ensure_tables(conn)
        return conn, False
    db = open_db()
    _ensure_tables(db)
    return db, True


def _close_if_owned(conn: Any, owns_conn: bool) -> None:
    if owns_conn:
        conn.close()


def _fetchone_dict(cur: Any) -> dict[str, Any] | None:
    row = cur.fetchone()
    if row is None:
        return None
    return dict(row)


def get_holding(
    *,
    ticker: str,
    is_simulated: bool,
    conn: Any | None = None,
) -> dict[str, Any] | None:
    try:
        db, owns_conn = _resolve_conn(conn)
    except RuntimeError:
        return None
    try:
        with db.cursor() as cur:
            cur.execute(
                """
                SELECT id, ticker, quantity, avg_price, notes, needs_review, is_simulated,
                       created_at, updated_at
                FROM equity_holdings
                WHERE ticker = %s AND COALESCE(is_simulated, 0) = %s
                """,
                (_normalize_ticker(ticker), 1 if is_simulated else 0),
            )
            row = _fetchone_dict(cur)
            if row is None:
                return None
            row["quantity"] = int(row.get("quantity") or 0)
            row["avg_price"] = float(row.get("avg_price") or 0.0)
            row["needs_review"] = bool(row.get("needs_review") or 0)
            row["is_simulated"] = bool(row.get("is_simulated") or 0)
            return row
    finally:
        _close_if_owned(db, owns_conn)


def list_holdings(
    *,
    is_simulated: bool | None = None,
    conn: Any | None = None,
) -> list[dict[str, Any]]:
    try:
        db, owns_conn = _resolve_conn(conn)
    except RuntimeError:
        return []
    try:
        clauses: list[str] = []
        params: list[object] = []
        if is_simulated is not None:
            clauses.append("COALESCE(is_simulated, 0) = %s")
            params.append(1 if is_simulated else 0)
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        with db.cursor() as cur:
            cur.execute(
                f"""
                SELECT id, ticker, quantity, avg_price, notes, needs_review, is_simulated,
                       created_at, updated_at
                FROM equity_holdings
                {where}
                ORDER BY ticker ASC, is_simulated ASC
                """,
                tuple(params),
            )
            rows = []
            for row in cur.fetchall():
                payload = dict(row)
                payload["quantity"] = int(payload.get("quantity") or 0)
                payload["avg_price"] = float(payload.get("avg_price") or 0.0)
                payload["needs_review"] = bool(payload.get("needs_review") or 0)
                payload["is_simulated"] = bool(payload.get("is_simulated") or 0)
                rows.append(payload)
            return rows
    finally:
        _close_if_owned(db, owns_conn)


def list_holding_events(
    *,
    ticker: str | None = None,
    event_type: str | None = None,
    is_simulated: bool | None = None,
    related_position_id: int | None = None,
    limit: int = 50,
    conn: Any | None = None,
) -> list[dict[str, Any]]:
    try:
        db, owns_conn = _resolve_conn(conn)
    except RuntimeError:
        return []
    try:
        clauses: list[str] = []
        params: list[object] = []
        if ticker:
            clauses.append("ticker = %s")
            params.append(_normalize_ticker(ticker))
        if event_type:
            clauses.append("event_type = %s")
            params.append(str(event_type).strip().upper())
        if is_simulated is not None:
            clauses.append("COALESCE(is_simulated, 0) = %s")
            params.append(1 if is_simulated else 0)
        if related_position_id is not None:
            clauses.append("related_position_id = %s")
            params.append(int(related_position_id))
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        with db.cursor() as cur:
            cur.execute(
                f"""
                SELECT id, ticker, event_date, event_type, qty_delta,
                       quantity_before, quantity_after, avg_price_before, avg_price_after,
                       price_reference, fees, notes, related_position_id, is_simulated, created_at
                FROM equity_holding_events
                {where}
                ORDER BY event_date DESC, id DESC
                LIMIT %s
                """,
                (*params, int(limit)),
            )
            rows = []
            for row in cur.fetchall():
                payload = dict(row)
                payload["qty_delta"] = int(payload.get("qty_delta") or 0)
                payload["quantity_before"] = int(payload.get("quantity_before") or 0)
                payload["quantity_after"] = int(payload.get("quantity_after") or 0)
                payload["avg_price_before"] = (
                    float(payload["avg_price_before"])
                    if payload.get("avg_price_before") is not None
                    else None
                )
                payload["avg_price_after"] = (
                    float(payload["avg_price_after"])
                    if payload.get("avg_price_after") is not None
                    else None
                )
                payload["price_reference"] = (
                    float(payload["price_reference"])
                    if payload.get("price_reference") is not None
                    else None
                )
                payload["fees"] = float(payload.get("fees") or 0.0)
                payload["is_simulated"] = bool(payload.get("is_simulated") or 0)
                rows.append(payload)
            return rows
    finally:
        _close_if_owned(db, owns_conn)


def _load_open_positions(
    *,
    is_simulated: bool | None = None,
    conn: Any | None = None,
    positions_open: Sequence[Mapping[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    if positions_open is not None:
        return [dict(pos) for pos in positions_open]
    try:
        return list_positions(include_closed=False, is_simulated=is_simulated, conn=conn)
    except RuntimeError:
        return []


def _reserved_call_totals(
    *,
    ticker: str,
    is_simulated: bool,
    exclude_position_id: int | None = None,
    conn: Any | None = None,
    positions_open: Sequence[Mapping[str, Any]] | None = None,
) -> tuple[int, int]:
    reserved_qty = 0
    call_count = 0
    normalized = _normalize_ticker(ticker)
    for pos in _load_open_positions(
        is_simulated=is_simulated,
        conn=conn,
        positions_open=positions_open,
    ):
        if bool(pos.get("is_simulated") or 0) != bool(is_simulated):
            continue
        if exclude_position_id is not None:
            try:
                if int(pos.get("id") or 0) == int(exclude_position_id):
                    continue
            except (TypeError, ValueError):
                pass
        if not _is_reserved_call_position(pos):
            continue
        if _normalize_ticker(pos.get("underlying")) != normalized:
            continue
        try:
            open_qty = int(pos.get("open_qty") or pos.get("qty") or 0)
        except (TypeError, ValueError):
            open_qty = 0
        if open_qty <= 0:
            continue
        reserved_qty += open_qty
        call_count += 1
    return reserved_qty, call_count


def _legacy_stock_totals(
    *,
    ticker: str,
    is_simulated: bool,
    conn: Any | None = None,
    positions_open: Sequence[Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    normalized = _normalize_ticker(ticker)
    total_qty = 0
    weighted_cost = 0.0
    distinct_prices: set[float] = set()
    position_ids: list[int] = []

    for pos in _load_open_positions(
        is_simulated=is_simulated,
        conn=conn,
        positions_open=positions_open,
    ):
        if bool(pos.get("is_simulated") or 0) != bool(is_simulated):
            continue
        if not _is_legacy_stock_position(pos):
            continue
        canonical = _canonical_stock_ticker(
            ticker=pos.get("ticker"),
            underlying=pos.get("underlying"),
        )
        if canonical != normalized:
            continue
        try:
            open_qty = int(pos.get("open_qty") or pos.get("qty") or 0)
        except (TypeError, ValueError):
            open_qty = 0
        if open_qty <= 0:
            continue
        entry_price = float(pos.get("entry_price") or 0.0)
        total_qty += open_qty
        weighted_cost += entry_price * open_qty
        if entry_price > 0:
            distinct_prices.add(round(entry_price, 8))
        try:
            position_ids.append(int(pos.get("id") or 0))
        except (TypeError, ValueError):
            pass

    avg_price = (weighted_cost / total_qty) if total_qty > 0 else None
    price_status = "empty"
    if total_qty > 0:
        price_status = "ok" if len(distinct_prices) <= 1 else "review"
    return {
        "ticker": normalized,
        "quantity": int(total_qty),
        "avg_price": avg_price,
        "price_status": price_status,
        "legacy_position_ids": [pid for pid in position_ids if pid > 0],
    }


def get_holding_snapshot(
    *,
    ticker: str,
    is_simulated: bool,
    exclude_position_id: int | None = None,
    conn: Any | None = None,
    positions_open: Sequence[Mapping[str, Any]] | None = None,
) -> dict[str, Any]:
    normalized = _normalize_ticker(ticker)
    holding = get_holding(ticker=normalized, is_simulated=is_simulated, conn=conn)
    reserved_qty, call_count = _reserved_call_totals(
        ticker=normalized,
        is_simulated=is_simulated,
        exclude_position_id=exclude_position_id,
        conn=conn,
        positions_open=positions_open,
    )

    if holding is not None:
        total_qty = int(holding.get("quantity") or 0)
        avg_price = float(holding.get("avg_price") or 0.0) if total_qty > 0 else None
        price_status = "review" if bool(holding.get("needs_review")) else ("ok" if total_qty > 0 else "empty")
        source = "holding"
        holding_id = holding.get("id")
        notes = holding.get("notes")
        legacy = _legacy_stock_totals(
            ticker=normalized,
            is_simulated=is_simulated,
            conn=conn,
            positions_open=positions_open,
        )
    else:
        legacy = _legacy_stock_totals(
            ticker=normalized,
            is_simulated=is_simulated,
            conn=conn,
            positions_open=positions_open,
        )
        total_qty = int(legacy.get("quantity") or 0)
        avg_price = legacy.get("avg_price")
        price_status = legacy.get("price_status") or "empty"
        source = "legacy" if total_qty > 0 else "empty"
        holding_id = None
        notes = None

    coverage_gap = max(int(reserved_qty) - int(total_qty), 0)
    return {
        "holding_id": holding_id,
        "ticker": normalized,
        "is_simulated": bool(is_simulated),
        "shares_total": int(total_qty),
        "shares_reserved": int(reserved_qty),
        "shares_free": max(int(total_qty) - int(reserved_qty), 0),
        "avg_price": avg_price,
        "price_status": price_status,
        "coverage_gap": coverage_gap,
        "coverage_status": "ok" if coverage_gap == 0 else "insufficient",
        "reserved_calls_count": int(call_count),
        "stock_positions_count": 1 if holding is not None else len(legacy.get("legacy_position_ids") or []),
        "source": source,
        "notes": notes,
        "legacy_position_ids": legacy.get("legacy_position_ids") or [],
    }


def validate_covered_call_availability(
    *,
    ticker: str,
    qty: int,
    is_simulated: bool,
    exclude_position_id: int | None = None,
    conn: Any | None = None,
) -> dict[str, Any]:
    normalized = _normalize_ticker(ticker)
    if not normalized:
        raise HoldingValidationError(
            "Nao foi possivel identificar o ativo-base da covered call.",
            ticker=None,
        )

    snapshot = get_holding_snapshot(
        ticker=normalized,
        is_simulated=is_simulated,
        exclude_position_id=exclude_position_id,
        conn=conn,
    )
    total_qty = int(snapshot.get("shares_total") or 0)
    free_qty = int(snapshot.get("shares_free") or 0)
    reserved_qty = int(snapshot.get("shares_reserved") or 0)

    if total_qty <= 0:
        raise HoldingValidationError(
            (
                f"Nao foi possivel cadastrar a covered call de {normalized}: "
                "primeiro informe o estoque consolidado do ativo na tela de Covered Call."
            ),
            ticker=normalized,
        )
    if int(qty or 0) > free_qty:
        raise HoldingValidationError(
            (
                f"Nao foi possivel salvar a venda coberta de {normalized}: "
                f"estoque total {total_qty}, ja reservado {reserved_qty}, livre {free_qty} e "
                f"quantidade da call {int(qty or 0)}. O cliente nao pode vender call a descoberto."
            ),
            ticker=normalized,
        )
    return snapshot


def list_holding_snapshots(
    *,
    underlying_filter: str | None = None,
    is_simulated: bool | None = None,
    conn: Any | None = None,
    positions_open: Sequence[Mapping[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    requested = _normalize_ticker(underlying_filter)
    snapshots: list[dict[str, Any]] = []
    tickers_by_mode: set[tuple[str, bool]] = set()

    for row in list_holdings(is_simulated=is_simulated, conn=conn):
        ticker = _normalize_ticker(row.get("ticker"))
        if requested and ticker != requested:
            continue
        tickers_by_mode.add((ticker, bool(row.get("is_simulated") or 0)))

    open_positions = _load_open_positions(
        is_simulated=is_simulated,
        conn=conn,
        positions_open=positions_open,
    )
    for pos in open_positions:
        mode = bool(pos.get("is_simulated") or 0)
        if is_simulated is not None and mode != bool(is_simulated):
            continue
        canonical = ""
        if _is_legacy_stock_position(pos):
            canonical = _canonical_stock_ticker(
                ticker=pos.get("ticker"),
                underlying=pos.get("underlying"),
            )
        elif _is_reserved_call_position(pos):
            canonical = _normalize_ticker(pos.get("underlying"))
        if not canonical:
            continue
        if requested and canonical != requested:
            continue
        tickers_by_mode.add((canonical, mode))

    for ticker, mode in sorted(tickers_by_mode):
        snapshots.append(
            get_holding_snapshot(
                ticker=ticker,
                is_simulated=mode,
                conn=conn,
                positions_open=open_positions,
            )
        )

    return sorted(
        snapshots,
        key=lambda item: (
            item["ticker"] != requested if requested else False,
            -int(item.get("shares_total") or 0),
            item["ticker"],
            item["is_simulated"],
        ),
    )


def _append_event(
    *,
    conn: Any,
    ticker: str,
    event_date: str,
    event_type: str,
    qty_delta: int,
    quantity_before: int,
    quantity_after: int,
    avg_price_before: float | None,
    avg_price_after: float | None,
    price_reference: float | None,
    notes: str | None,
    related_position_id: int | None,
    is_simulated: bool,
    fees: float = 0.0,
) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO equity_holding_events (
                ticker,
                event_date,
                event_type,
                qty_delta,
                quantity_before,
                quantity_after,
                avg_price_before,
                avg_price_after,
                price_reference,
                fees,
                notes,
                related_position_id,
                is_simulated
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                _normalize_ticker(ticker),
                event_date,
                str(event_type).strip().upper(),
                int(qty_delta),
                int(quantity_before),
                int(quantity_after),
                float(avg_price_before) if avg_price_before is not None else None,
                float(avg_price_after) if avg_price_after is not None else None,
                float(price_reference) if price_reference is not None else None,
                float(fees or 0.0),
                notes,
                int(related_position_id) if related_position_id is not None else None,
                1 if is_simulated else 0,
            ),
        )


def upsert_holding(
    *,
    ticker: str,
    quantity: int,
    avg_price: float,
    is_simulated: bool,
    notes: str | None = None,
    event_date: str | None = None,
    event_type: str = "MANUAL_SET",
    related_position_id: int | None = None,
    allow_below_reserved: bool = False,
    conn: Any | None = None,
) -> dict[str, Any]:
    normalized = _normalize_ticker(ticker)
    if not normalized or not _looks_like_equity_ticker(normalized):
        raise HoldingValidationError(
            "Informe um ticker de acao valido para o estoque consolidado.",
            ticker=normalized or None,
        )

    qty = int(quantity or 0)
    avg = float(avg_price or 0.0)
    if qty < 0:
        raise HoldingValidationError(
            f"O estoque consolidado de {normalized} nao pode ficar negativo.",
            ticker=normalized,
        )
    if qty > 0 and avg <= 0:
        raise HoldingValidationError(
            f"Informe um preco medio maior que zero para {normalized}.",
            ticker=normalized,
        )

    db, owns_conn = _resolve_conn(conn)
    try:
        snapshot = get_holding_snapshot(
            ticker=normalized,
            is_simulated=is_simulated,
            conn=db,
        )
        reserved_qty = int(snapshot.get("shares_reserved") or 0)
        if not allow_below_reserved and qty < reserved_qty:
            raise HoldingValidationError(
                (
                    f"Nao foi possivel salvar o estoque de {normalized}: existem "
                    f"{reserved_qty} acoes reservadas em calls abertas e o saldo informado "
                    f"foi {qty}. Reduza primeiro as calls abertas ou informe um estoque maior."
                ),
                ticker=normalized,
            )

        current = get_holding(ticker=normalized, is_simulated=is_simulated, conn=db)
        before_qty = int(current.get("quantity") or 0) if current else int(snapshot.get("shares_total") or 0)
        before_avg = (
            float(current.get("avg_price") or 0.0)
            if current and int(current.get("quantity") or 0) > 0
            else snapshot.get("avg_price")
        )

        with db.cursor() as cur:
            if current is None:
                cur.execute(
                    """
                    INSERT INTO equity_holdings (ticker, quantity, avg_price, notes, needs_review, is_simulated)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (normalized, qty, avg if qty > 0 else 0.0, notes, 0, 1 if is_simulated else 0),
                )
                holding_id = int(cur.fetchone()["id"])
            else:
                holding_id = int(current["id"])
                cur.execute(
                    """
                    UPDATE equity_holdings
                    SET quantity = %s,
                        avg_price = %s,
                        notes = %s,
                        needs_review = 0,
                        updated_at = NOW()
                    WHERE id = %s
                    """,
                    (qty, avg if qty > 0 else 0.0, notes, holding_id),
                )

        _append_event(
            conn=db,
            ticker=normalized,
            event_date=event_date or dt.date.today().isoformat(),
            event_type=event_type,
            qty_delta=qty - before_qty,
            quantity_before=before_qty,
            quantity_after=qty,
            avg_price_before=before_avg,
            avg_price_after=(avg if qty > 0 else None),
            price_reference=(avg if qty > 0 else None),
            notes=notes,
            related_position_id=related_position_id,
            is_simulated=is_simulated,
        )

        if owns_conn:
            db.commit()
        return get_holding_snapshot(ticker=normalized, is_simulated=is_simulated, conn=db)
    except Exception:
        if owns_conn:
            db.rollback()
        raise
    finally:
        _close_if_owned(db, owns_conn)


def apply_put_assignment_to_holding(
    *,
    ticker: str,
    qty: int,
    strike: float,
    purchase_fees: float,
    date: str,
    is_simulated: bool,
    related_position_id: int | None = None,
    conn: Any | None = None,
) -> dict[str, Any]:
    normalized = _normalize_ticker(ticker)
    qty_val = int(qty or 0)
    strike_val = float(strike or 0.0)
    fees_val = float(purchase_fees or 0.0)
    if qty_val <= 0 or strike_val <= 0 or not math.isfinite(fees_val) or fees_val < 0:
        raise HoldingValidationError(
            f"Exercicio de put invalido para {normalized}.",
            ticker=normalized,
        )

    db, owns_conn = _resolve_conn(conn)
    try:
        current = get_holding(ticker=normalized, is_simulated=is_simulated, conn=db)
        snapshot = get_holding_snapshot(ticker=normalized, is_simulated=is_simulated, conn=db)
        before_qty = int(current.get("quantity") or 0) if current else int(snapshot.get("shares_total") or 0)
        before_avg = (
            float(current.get("avg_price") or 0.0)
            if current and int(current.get("quantity") or 0) > 0
            else snapshot.get("avg_price")
        )
        after_qty = before_qty + qty_val
        acquisition_cost = (strike_val * qty_val) + fees_val
        if before_qty <= 0:
            after_avg = acquisition_cost / qty_val
            needs_review = False
        elif before_avg is not None and float(before_avg) > 0:
            after_avg = ((float(before_avg) * before_qty) + acquisition_cost) / after_qty
            needs_review = False
        else:
            after_avg = float(before_avg or 0.0)
            needs_review = True

        notes = (
            (
                f"Exercicio da put: revise o PM consolidado de {normalized}; "
                f"despesas da compra: R$ {fees_val:.2f}."
            )
            if needs_review
            else (
                f"Exercicio da put {related_position_id or ''}; PM recalculado; "
                f"despesas da compra: R$ {fees_val:.2f}"
            ).strip()
        )

        with db.cursor() as cur:
            if current is None:
                cur.execute(
                    """
                    INSERT INTO equity_holdings (ticker, quantity, avg_price, notes, needs_review, is_simulated)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (normalized, after_qty, after_avg if after_qty > 0 else 0.0, notes, 1 if needs_review else 0, 1 if is_simulated else 0),
                )
            else:
                cur.execute(
                    """
                    UPDATE equity_holdings
                    SET quantity = %s,
                        avg_price = %s,
                        notes = %s,
                        needs_review = %s,
                        updated_at = NOW()
                    WHERE id = %s
                    """,
                    (
                        after_qty,
                        after_avg if after_qty > 0 else 0.0,
                        notes,
                        1 if needs_review else 0,
                        int(current["id"]),
                    ),
                )

        _append_event(
            conn=db,
            ticker=normalized,
            event_date=date,
            event_type="PUT_ASSIGNMENT",
            qty_delta=qty_val,
            quantity_before=before_qty,
            quantity_after=after_qty,
            avg_price_before=before_avg,
            avg_price_after=(after_avg if after_qty > 0 else None),
            price_reference=strike_val,
            notes=notes,
            related_position_id=related_position_id,
            is_simulated=is_simulated,
            fees=fees_val,
        )
        if owns_conn:
            db.commit()
        return get_holding_snapshot(ticker=normalized, is_simulated=is_simulated, conn=db)
    except Exception:
        if owns_conn:
            db.rollback()
        raise
    finally:
        _close_if_owned(db, owns_conn)


def apply_call_exercise_to_holding(
    *,
    ticker: str,
    qty: int,
    strike: float,
    sale_fees: float,
    date: str,
    is_simulated: bool,
    related_position_id: int | None = None,
    conn: Any | None = None,
) -> dict[str, Any]:
    normalized = _normalize_ticker(ticker)
    qty_val = int(qty or 0)
    strike_val = float(strike or 0.0)
    fees_val = float(sale_fees or 0.0)
    if qty_val <= 0 or strike_val <= 0 or not math.isfinite(fees_val) or fees_val < 0:
        raise HoldingValidationError(
            f"Exercicio de call invalido para {normalized}.",
            ticker=normalized,
        )

    db, owns_conn = _resolve_conn(conn)
    try:
        snapshot = get_holding_snapshot(ticker=normalized, is_simulated=is_simulated, conn=db)
        before_qty = int(snapshot.get("shares_total") or 0)
        before_avg = snapshot.get("avg_price")
        if before_qty < qty_val:
            raise HoldingValidationError(
                (
                    f"Nao foi possivel exercer a call de {normalized}: o estoque consolidado "
                    f"tem {before_qty} acoes e a opcao exige {qty_val}."
                ),
                ticker=normalized,
            )

        current = get_holding(ticker=normalized, is_simulated=is_simulated, conn=db)
        after_qty = before_qty - qty_val
        after_avg = float(before_avg or 0.0) if after_qty > 0 else 0.0
        notes = f"Baixa automatica por exercicio da call {related_position_id or ''}".strip()

        with db.cursor() as cur:
            if current is None:
                cur.execute(
                    """
                    INSERT INTO equity_holdings (ticker, quantity, avg_price, notes, needs_review, is_simulated)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (normalized, after_qty, after_avg, notes, 0, 1 if is_simulated else 0),
                )
            else:
                cur.execute(
                    """
                    UPDATE equity_holdings
                    SET quantity = %s,
                        avg_price = %s,
                        notes = %s,
                        needs_review = 0,
                        updated_at = NOW()
                    WHERE id = %s
                    """,
                    (after_qty, after_avg, notes, int(current["id"])),
                )

        _append_event(
            conn=db,
            ticker=normalized,
            event_date=date,
            event_type="CALL_EXERCISE",
            qty_delta=-qty_val,
            quantity_before=before_qty,
            quantity_after=after_qty,
            avg_price_before=before_avg,
            avg_price_after=(after_avg if after_qty > 0 else None),
            price_reference=strike_val,
            notes=notes,
            related_position_id=related_position_id,
            is_simulated=is_simulated,
            fees=fees_val,
        )
        if owns_conn:
            db.commit()
        return {
            **get_holding_snapshot(ticker=normalized, is_simulated=is_simulated, conn=db),
            "consumed_avg_price": before_avg,
            "sold_qty": qty_val,
            "strike": strike_val,
        }
    except Exception:
        if owns_conn:
            db.rollback()
        raise
    finally:
        _close_if_owned(db, owns_conn)


__all__ = [
    "HoldingValidationError",
    "apply_call_exercise_to_holding",
    "apply_put_assignment_to_holding",
    "get_holding",
    "get_holding_snapshot",
    "list_holding_events",
    "list_holding_snapshots",
    "list_holdings",
    "upsert_holding",
    "validate_covered_call_availability",
]
