"""Recibos idempotentes para comandos financeiros enviados pela interface."""

from __future__ import annotations

import re
import uuid
from dataclasses import dataclass
from typing import Any


_HASH_RE = re.compile(r"^[0-9a-f]{64}$")


def _execute(conn: Any, query: str, params: tuple[object, ...] = ()) -> Any:
    """Aceita o adaptador interno e a conexão psycopg direta da CLI."""

    if hasattr(conn, "backend"):
        return conn.execute(query, params)
    return conn.execute(query.replace("?", "%s"), params)


def _value(row: Any, key: str, index: int = 0) -> Any:
    if isinstance(row, dict):
        return row.get(key)
    try:
        return row[key]
    except (IndexError, KeyError, TypeError):
        try:
            return row[index]
        except (IndexError, KeyError, TypeError):
            return None


class OperationReceiptError(ValueError):
    """A chave de confirmação não pode ser usada com este comando."""


@dataclass(frozen=True)
class OperationReceipt:
    id: int
    replayed: bool = False
    result_entity_type: str | None = None
    result_entity_id: int | None = None


def ensure_operation_receipts(conn: Any, *, commit: bool = False) -> None:
    """Instala a tabela aditiva de recibos no schema ativo."""

    _execute(
        conn,
        """
        CREATE TABLE IF NOT EXISTS operation_receipts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            completed_at TIMESTAMPTZ,
            command_name TEXT NOT NULL,
            idempotency_key UUID NOT NULL,
            payload_hash TEXT NOT NULL,
            actor TEXT NOT NULL DEFAULT 'system',
            result_entity_type TEXT,
            result_entity_id BIGINT,
            CHECK (char_length(command_name) BETWEEN 1 AND 128),
            CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
            UNIQUE (command_name, idempotency_key)
        )
        """,
    )
    _execute(
        conn,
        """
        CREATE INDEX IF NOT EXISTS idx_operation_receipts_created_at
        ON operation_receipts (created_at DESC)
        """,
    )
    if commit:
        conn.commit()


def _normalized_command(value: str) -> str:
    command = (value or "").strip()
    if not command or len(command) > 128:
        raise OperationReceiptError("Comando de registro inválido.")
    return command


def _normalized_key(value: str) -> str:
    try:
        return str(uuid.UUID(str(value or "").strip()))
    except (AttributeError, ValueError) as exc:
        raise OperationReceiptError(
            "Confirmação do formulário inválida ou expirada. Recarregue a página e tente novamente."
        ) from exc


def _normalized_hash(value: str) -> str:
    payload_hash = (value or "").strip().lower()
    if not _HASH_RE.fullmatch(payload_hash):
        raise OperationReceiptError(
            "Conteúdo da confirmação inválido. Recarregue a página."
        )
    return payload_hash


def claim_operation_receipt(
    conn: Any,
    *,
    command_name: str,
    idempotency_key: str,
    payload_hash: str,
    actor: str | None = None,
) -> OperationReceipt:
    """Reserva ou recupera um recibo na mesma transação do comando.

    A restrição única é a defesa decisiva contra dois POSTs concorrentes. Um
    recibo só é concluído junto da operação; se ela falhar, o rollback remove
    também a reserva e permite uma tentativa posterior correta.
    """

    ensure_operation_receipts(conn)
    command = _normalized_command(command_name)
    key = _normalized_key(idempotency_key)
    fingerprint = _normalized_hash(payload_hash)
    normalized_actor = (actor or "").strip() or "system"
    if len(normalized_actor) > 128:
        raise OperationReceiptError("Responsável pelo registro excede 128 caracteres.")

    row = _execute(
        conn,
        """
        INSERT INTO operation_receipts (
            command_name, idempotency_key, payload_hash, actor
        )
        VALUES (?, ?::uuid, ?, ?)
        ON CONFLICT (command_name, idempotency_key) DO NOTHING
        RETURNING id
        """,
        (command, key, fingerprint, normalized_actor),
    ).fetchone()
    if row is not None:
        return OperationReceipt(id=int(_value(row, "id")))

    existing = _execute(
        conn,
        """
        SELECT id, payload_hash, result_entity_type, result_entity_id
        FROM operation_receipts
        WHERE command_name = ? AND idempotency_key = ?::uuid
        FOR UPDATE
        """,
        (command, key),
    ).fetchone()
    if existing is None:
        raise RuntimeError("Não foi possível recuperar a confirmação da operação.")
    if str(_value(existing, "payload_hash", 1)) != fingerprint:
        raise OperationReceiptError(
            "Esta confirmação já foi usada com outros dados. Recarregue o formulário antes de registrar."
        )

    result_id = _value(existing, "result_entity_id", 3)
    if result_id is None:
        raise RuntimeError(
            "A operação anterior ainda não foi concluída. Tente novamente."
        )
    return OperationReceipt(
        id=int(_value(existing, "id")),
        replayed=True,
        result_entity_type=_value(existing, "result_entity_type", 2),
        result_entity_id=int(result_id),
    )


def complete_operation_receipt(
    conn: Any,
    *,
    receipt_id: int,
    result_entity_type: str,
    result_entity_id: int,
) -> None:
    entity_type = (result_entity_type or "").strip()
    if not entity_type or len(entity_type) > 64 or int(result_entity_id) <= 0:
        raise OperationReceiptError("Resultado do registro inválido.")
    cur = _execute(
        conn,
        """
        UPDATE operation_receipts
        SET completed_at = CURRENT_TIMESTAMP,
            result_entity_type = ?,
            result_entity_id = ?
        WHERE id = ? AND result_entity_id IS NULL
        """,
        (entity_type, int(result_entity_id), int(receipt_id)),
    )
    if getattr(cur, "rowcount", 1) != 1:
        raise RuntimeError("Não foi possível finalizar o recibo da operação.")


def install_operation_receipts() -> None:
    """Instala recibos no schema configurado, sem alterar operações existentes."""

    from .db import open_db

    conn = open_db()
    try:
        ensure_operation_receipts(conn, commit=True)
    finally:
        conn.close()


__all__ = [
    "OperationReceipt",
    "OperationReceiptError",
    "claim_operation_receipt",
    "complete_operation_receipt",
    "ensure_operation_receipts",
    "install_operation_receipts",
]
