from __future__ import annotations

import datetime as dt
import re
from typing import Any, Iterable, List, Mapping, Optional

from .config import (
    get_postgres_schema,
)
from .db_health import resolve_postgres_target
from .snapshot_repository import fetch_latest_option_snapshots
from .utils import infer_option_type, parse_ptbr_number

_UNSET = object()


class _PgResult:
    def __init__(
        self,
        rows: Optional[list[Mapping[str, Any]]] = None,
        *,
        rowcount: int = 0,
    ) -> None:
        self._rows = list(rows or [])
        self.rowcount = int(rowcount or 0)
        self.lastrowid = None

    def fetchone(self):
        if not self._rows:
            return None
        return self._rows[0]

    def fetchall(self):
        return list(self._rows)


class _DbConn:
    def __init__(
        self,
        *,
        backend: str,
        raw_conn: Any,
        pg_row_factory: Any = None,
    ) -> None:
        self.backend = backend
        self._raw_conn = raw_conn
        self._pg_row_factory = pg_row_factory

    def execute(self, query: str, params: Iterable[object] = ()):
        query_pg = query.replace("%", "%%").replace("?", "%s")
        with self._raw_conn.cursor(row_factory=self._pg_row_factory) as cur:
            cur.execute(query_pg, tuple(params))
            rowcount = int(cur.rowcount or 0)
            if cur.description is None:
                return _PgResult([], rowcount=rowcount)
            rows = cur.fetchall()
            return _PgResult(rows, rowcount=rowcount)

    def commit(self) -> None:
        self._raw_conn.commit()

    def close(self) -> None:
        self._raw_conn.close()

    def rollback(self) -> None:
        self._raw_conn.rollback()

    @property
    def in_transaction(self) -> bool:
        info = getattr(self._raw_conn, "info", None)
        status = getattr(info, "transaction_status", None)
        if status is None:
            return False
        status_name = str(getattr(status, "name", status)).upper()
        return status_name not in {"IDLE", "UNKNOWN"}


def _first_col(row: Any) -> Any:
    if row is None:
        return None
    if isinstance(row, Mapping):
        values = list(row.values())
        return values[0] if values else None
    try:
        return row[0]
    except Exception:
        return None


def _quote_ident(value: str) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def _connect_postgres(*, ensure_schema: bool = False) -> _DbConn:
    target, errors = resolve_postgres_target()
    if target is None:
        reasons = "; ".join(errors) if errors else "configuração ausente"
        raise RuntimeError(f"PostgreSQL não configurado: {reasons}")
    try:
        import psycopg
        from psycopg.rows import dict_row
    except Exception as exc:
        raise RuntimeError(
            "Driver psycopg não encontrado. Instale com: uv add psycopg[binary]"
        ) from exc

    schema = get_postgres_schema()
    raw_conn = psycopg.connect(target.dsn, row_factory=dict_row)
    with raw_conn.cursor() as cur:
        cur.execute(f"CREATE SCHEMA IF NOT EXISTS {_quote_ident(schema)}")
        cur.execute(f"SET search_path TO {_quote_ident(schema)}")
    conn = _DbConn(backend="postgres", raw_conn=raw_conn, pg_row_factory=dict_row)
    if ensure_schema:
        _ensure_tables(conn, commit=True)
    return conn


def _connect(*, ensure_schema: bool = False) -> _DbConn:
    return _connect_postgres(ensure_schema=ensure_schema)


def _wrap_existing_conn(conn: Any) -> _DbConn:
    if isinstance(conn, _DbConn):
        return conn
    return _DbConn(backend="postgres", raw_conn=conn)


def _resolve_conn(
    conn: Optional[Any],
    *,
    ensure_schema: bool = False,
) -> tuple[_DbConn, bool]:
    if conn is None:
        return _connect(ensure_schema=ensure_schema), True
    db = _wrap_existing_conn(conn)
    if ensure_schema:
        _ensure_tables(db, commit=not db.in_transaction)
    return db, False


def _ensure_tables(conn: _DbConn, *, commit: bool) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS positions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ticker TEXT NOT NULL,
            underlying TEXT NOT NULL,
            trade_date TEXT NOT NULL,
            qty INTEGER NOT NULL,
            entry_price DOUBLE PRECISION NOT NULL,
            fees DOUBLE PRECISION DEFAULT 0,
            trade_type TEXT DEFAULT 'swing',
            side TEXT DEFAULT 'long',
            irrf DOUBLE PRECISION,
            status TEXT NOT NULL DEFAULT 'open',
            exit_date TEXT,
            exit_price DOUBLE PRECISION,
            notes TEXT,
            partial_date TEXT,
            partial_price DOUBLE PRECISION,
            partial_qty INTEGER,
            exit_reason TEXT,
            is_simulated INTEGER DEFAULT 0,
            parent_position_id BIGINT,
            strategy_tag TEXT
        )
        """
    )

    _ensure_position_columns(conn)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_positions_ticker ON positions (ticker)")
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_positions_status_trade_date ON positions (status, trade_date DESC, id DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_positions_strategy_status ON positions (strategy_tag, status)"
    )
    _migrate_strategy_sides(conn)
    _migrate_stock_underlying_defaults(conn)
    if commit:
        conn.commit()


def _ensure_position_columns(conn: _DbConn) -> None:
    rows = conn.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'positions'
        """
    ).fetchall()
    existing = {str(r["column_name"]) for r in rows}
    columns = {
        "partial_date": "TEXT",
        "partial_price": "DOUBLE PRECISION",
        "partial_qty": "INTEGER",
        "exit_reason": "TEXT",
        "trade_type": "TEXT",
        "side": "TEXT DEFAULT 'long'",
        "irrf": "DOUBLE PRECISION",
        "is_simulated": "INTEGER DEFAULT 0",
        "parent_position_id": "BIGINT",
        "strategy_tag": "TEXT",
    }
    for col, col_type in columns.items():
        if col not in existing:
            conn.execute(
                f'ALTER TABLE positions ADD COLUMN IF NOT EXISTS "{col}" {col_type}'
            )


def _migrate_strategy_sides(conn: _DbConn) -> None:
    """Marca como vendidas posições de estratégia short (cash_put/covered_call)."""
    try:
        conn.execute(
            """
            UPDATE positions
            SET side = 'short'
            WHERE LOWER(COALESCE(side, '')) != 'short'
              AND strategy_tag IN ('cash_put', 'covered_call')
              AND UPPER(COALESCE(ticker, '')) != UPPER(COALESCE(underlying, ''))
            """
        )
    except Exception:
        # Evita quebrar o fluxo em bancos antigos/parciais.
        return


def _migrate_stock_underlying_defaults(conn: _DbConn) -> None:
    """Preenche underlying vazio para ações em estoque, usando o próprio ticker."""

    try:
        conn.execute(
            """
            UPDATE positions
            SET underlying = UPPER(TRIM(ticker))
            WHERE COALESCE(TRIM(underlying), '') = ''
              AND LOWER(COALESCE(side, 'long')) != 'short'
              AND LOWER(COALESCE(strategy_tag, '')) NOT IN ('cash_put', 'covered_call', 'ranking')
              AND UPPER(TRIM(ticker)) ~ '^[A-Z]{4}[0-9]{1,2}$'
            """
        )
    except Exception:
        # Evita quebrar o fluxo em bancos antigos/parciais.
        return


def _normalize_ticker(value: str) -> str:
    return (value or "").strip().upper()


def _normalize_side(value: Optional[str]) -> str:
    text = (value or "").strip().lower()
    if text in {"short", "vendida", "vendido", "v"}:
        return "short"
    return "long"


def _looks_like_stock_ticker(value: str) -> bool:
    return bool(re.fullmatch(r"[A-Z]{4}[0-9]{1,2}", (value or "").strip().upper()))


def _table_exists(conn: _DbConn, table_name: str) -> bool:
    row = conn.execute("SELECT to_regclass(?)", (table_name,)).fetchone()
    return _first_col(row) is not None


def _row_as_dict(row: Any) -> dict[str, Any]:
    if row is None:
        return {}
    if isinstance(row, Mapping):
        return dict(row)
    try:
        return dict(row)
    except Exception:
        return {}


def _attach_snapshot_fields(
    row: Any,
    snapshot_map: Mapping[str, Mapping[str, Any]],
) -> dict[str, Any]:
    payload = _row_as_dict(row)
    ticker = (payload.get("ticker") or "").strip().upper()
    snapshot = snapshot_map.get(ticker)
    payload["last_snapshot_date"] = snapshot.get("snapshot_date") if snapshot else None
    payload["last_price_raw"] = snapshot.get("last_price_raw") if snapshot else None
    payload["last_score_total"] = snapshot.get("last_score_total") if snapshot else None
    payload["last_trend_flag"] = snapshot.get("last_trend_flag") if snapshot else None
    payload["last_vencimento"] = snapshot.get("last_vencimento") if snapshot else None
    payload["last_dias_uteis"] = snapshot.get("last_dias_uteis") if snapshot else None
    payload["last_underlying_price"] = (
        snapshot.get("last_underlying_price") if snapshot else None
    )
    payload["last_extrinsic_pct_spot"] = (
        snapshot.get("last_extrinsic_pct_spot") if snapshot else None
    )
    payload["last_pct_2x"] = snapshot.get("last_pct_2x") if snapshot else None
    payload["last_strike"] = snapshot.get("last_strike") if snapshot else None
    return payload


def add_position(
    *,
    ticker: str,
    underlying: str,
    trade_date: str,
    qty: int,
    entry_price: float,
    fees: float = 0.0,
    trade_type: str = "swing",
    side: str = "long",
    irrf: Optional[float] = None,
    notes: Optional[str] = None,
    partial_date: Optional[str] = None,
    partial_price: Optional[float] = None,
    partial_qty: Optional[int] = None,
    exit_reason: Optional[str] = None,
    is_simulated: bool = False,
    parent_position_id: Optional[int] = None,
    strategy_tag: Optional[str] = None,
    conn: Optional[Any] = None,
) -> int:
    db, owns_conn = _resolve_conn(conn, ensure_schema=True)
    normalized_ticker = _normalize_ticker(ticker)
    normalized_underlying = _normalize_ticker(underlying)
    if not normalized_underlying and _looks_like_stock_ticker(normalized_ticker):
        normalized_underlying = normalized_ticker
    params = (
        normalized_ticker,
        normalized_underlying,
        trade_date,
        int(qty),
        float(entry_price),
        float(fees or 0.0),
        trade_type,
        _normalize_side(side),
        float(irrf) if irrf is not None else None,
        notes,
        partial_date,
        float(partial_price) if partial_price is not None else None,
        int(partial_qty) if partial_qty is not None else None,
        exit_reason,
        1 if is_simulated else 0,
        int(parent_position_id) if parent_position_id is not None else None,
        strategy_tag or None,
    )
    try:
        if db.backend == "postgres":
            row = db.execute(
                """
                INSERT INTO positions (
                    ticker,
                    underlying,
                    trade_date,
                    qty,
                    entry_price,
                    fees,
                    trade_type,
                    side,
                    irrf,
                    notes,
                    partial_date,
                    partial_price,
                    partial_qty,
                    exit_reason,
                    is_simulated,
                    parent_position_id,
                    strategy_tag
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """,
                params,
            ).fetchone()
            pos_id = _first_col(row)
        else:
            cur = db.execute(
                """
                INSERT INTO positions (
                    ticker,
                    underlying,
                    trade_date,
                    qty,
                    entry_price,
                    fees,
                    trade_type,
                    side,
                    irrf,
                    notes,
                    partial_date,
                    partial_price,
                    partial_qty,
                    exit_reason,
                    is_simulated,
                    parent_position_id,
                    strategy_tag
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                params,
            )
            pos_id = getattr(cur, "lastrowid", None)
        if pos_id is None:
            raise RuntimeError("Falha ao obter id da posição inserida.")
        if owns_conn:
            db.commit()
        return int(pos_id)
    finally:
        if owns_conn:
            db.close()


def close_position(
    *,
    position_id: int,
    exit_date: str,
    exit_price: float,
    exit_reason: Optional[str] = None,
    conn: Optional[Any] = None,
) -> None:
    db, owns_conn = _resolve_conn(conn, ensure_schema=True)
    cur = db.execute(
        """
        UPDATE positions
        SET status = 'closed',
            exit_date = ?,
            exit_price = ?,
            exit_reason = COALESCE(?, exit_reason)
        WHERE id = ? AND status = 'open'
        """,
        (exit_date, float(exit_price), exit_reason, int(position_id)),
    )
    if cur.rowcount == 0:
        if owns_conn:
            db.close()
        raise ValueError(f"Posição {position_id} não encontrada ou já fechada.")
    if owns_conn:
        db.commit()
        db.close()


def update_position(
    *,
    position_id: int,
    ticker: Any = _UNSET,
    underlying: Any = _UNSET,
    trade_date: Any = _UNSET,
    qty: Any = _UNSET,
    entry_price: Any = _UNSET,
    fees: Any = _UNSET,
    status: Any = _UNSET,
    exit_date: Any = _UNSET,
    exit_price: Any = _UNSET,
    notes: Any = _UNSET,
    partial_date: Any = _UNSET,
    partial_price: Any = _UNSET,
    partial_qty: Any = _UNSET,
    exit_reason: Any = _UNSET,
    trade_type: Any = _UNSET,
    side: Any = _UNSET,
    irrf: Any = _UNSET,
    is_simulated: Any = _UNSET,
    parent_position_id: Any = _UNSET,
    strategy_tag: Any = _UNSET,
    conn: Optional[Any] = None,
) -> None:
    fields = []
    params = []
    if ticker is not _UNSET:
        fields.append("ticker = ?")
        params.append(_normalize_ticker(ticker))
    if underlying is not _UNSET:
        fields.append("underlying = ?")
        params.append(_normalize_ticker(underlying))
    if trade_date is not _UNSET:
        fields.append("trade_date = ?")
        params.append(trade_date)
    if qty is not _UNSET:
        fields.append("qty = ?")
        params.append(int(qty))
    if entry_price is not _UNSET:
        fields.append("entry_price = ?")
        params.append(float(entry_price))
    if fees is not _UNSET:
        fields.append("fees = ?")
        params.append(float(fees))
    if status is not _UNSET:
        fields.append("status = ?")
        params.append(status)
    if exit_date is not _UNSET:
        fields.append("exit_date = ?")
        params.append(exit_date)
    if exit_price is not _UNSET:
        fields.append("exit_price = ?")
        params.append(float(exit_price) if exit_price is not None else None)
    if notes is not _UNSET:
        fields.append("notes = ?")
        params.append(notes)
    if partial_date is not _UNSET:
        fields.append("partial_date = ?")
        params.append(partial_date)
    if partial_price is not _UNSET:
        fields.append("partial_price = ?")
        params.append(float(partial_price) if partial_price is not None else None)
    if partial_qty is not _UNSET:
        fields.append("partial_qty = ?")
        params.append(int(partial_qty) if partial_qty is not None else None)
    if exit_reason is not _UNSET:
        fields.append("exit_reason = ?")
        params.append(exit_reason)
    if trade_type is not _UNSET:
        fields.append("trade_type = ?")
        params.append(trade_type)
    if side is not _UNSET:
        fields.append("side = ?")
        params.append(_normalize_side(side))
    if irrf is not _UNSET:
        fields.append("irrf = ?")
        params.append(float(irrf) if irrf is not None else None)
    if is_simulated is not _UNSET:
        fields.append("is_simulated = ?")
        params.append(1 if is_simulated else 0)
    if parent_position_id is not _UNSET:
        fields.append("parent_position_id = ?")
        params.append(int(parent_position_id) if parent_position_id is not None else None)
    if strategy_tag is not _UNSET:
        fields.append("strategy_tag = ?")
        params.append(strategy_tag)
    if not fields:
        return

    params.append(int(position_id))
    db, owns_conn = _resolve_conn(conn, ensure_schema=True)
    cur = db.execute(f"UPDATE positions SET {', '.join(fields)} WHERE id = ?", params)
    if cur.rowcount == 0:
        if owns_conn:
            db.close()
        raise ValueError(f"Posição {position_id} não encontrada.")
    if owns_conn:
        db.commit()
        db.close()


def delete_position(*, position_id: int, conn: Optional[Any] = None) -> None:
    db, owns_conn = _resolve_conn(conn, ensure_schema=True)
    db.execute("DELETE FROM positions WHERE id = ?", (int(position_id),))
    if owns_conn:
        db.commit()
        db.close()


def get_position(position_id: int, *, conn: Optional[Any] = None) -> Optional[dict]:
    db, owns_conn = _resolve_conn(conn)
    try:
        if not _table_exists(db, "positions"):
            return None
        row = db.execute("SELECT p.* FROM positions p WHERE p.id = ?", (int(position_id),)).fetchone()
        if not row:
            return None
        ticker = (_row_as_dict(row).get("ticker") or "").strip().upper()
        snapshot_map = fetch_latest_option_snapshots([ticker]) if ticker else {}
        return _row_to_dict(_attach_snapshot_fields(row, snapshot_map))
    finally:
        if owns_conn:
            db.close()


def list_positions(
    *,
    include_closed: bool = False,
    ticker: Optional[str] = None,
    only_closed: bool = False,
    ticker_contains: Optional[str] = None,
    underlying_contains: Optional[str] = None,
    strategy_tag: Optional[str] = None,
    trade_type: Optional[str] = None,
    is_simulated: Optional[bool] = None,
    conn: Optional[Any] = None,
) -> List[dict]:
    db, owns_conn = _resolve_conn(conn)
    try:
        if not _table_exists(db, "positions"):
            return []
        where: List[str] = []
        params: List[object] = []
        if only_closed:
            where.append("p.status = 'closed'")
        elif not include_closed:
            where.append("p.status = 'open'")
        if ticker:
            where.append("p.ticker = ?")
            params.append(_normalize_ticker(ticker))
        if ticker_contains:
            where.append("p.ticker LIKE ?")
            params.append(f"%{_normalize_ticker(ticker_contains)}%")
        if underlying_contains:
            where.append("p.underlying LIKE ?")
            params.append(f"%{_normalize_ticker(underlying_contains)}%")
        if trade_type:
            where.append("p.trade_type = ?")
            params.append((trade_type or "").strip().lower())
        if strategy_tag:
            if strategy_tag == "__none__":
                where.append("COALESCE(p.strategy_tag, '') = ''")
            else:
                where.append("p.strategy_tag = ?")
                params.append((strategy_tag or "").strip())
        if is_simulated is not None:
            where.append("COALESCE(p.is_simulated, 0) = ?")
            params.append(1 if is_simulated else 0)
        where_clause = f"WHERE {' AND '.join(where)}" if where else ""
        rows = db.execute(
            f"""
            SELECT p.*
            FROM positions p
            {where_clause}
            ORDER BY p.trade_date DESC, p.id DESC
            """,
            params,
        ).fetchall()
        tickers = [
            (_row_as_dict(row).get("ticker") or "").strip().upper()
            for row in rows
        ]
        snapshot_map = fetch_latest_option_snapshots(tickers)
        return [
            _row_to_dict(_attach_snapshot_fields(row, snapshot_map))
            for row in rows
        ]
    finally:
        if owns_conn:
            db.close()


def summarize_realized_positions(
    *,
    ticker_contains: Optional[str] = None,
    underlying_contains: Optional[str] = None,
    strategy_tag: Optional[str] = None,
    trade_type: Optional[str] = None,
    is_simulated: Optional[bool] = None,
    selected_year: Optional[int] = None,
    selected_month: Optional[int] = None,
    conn: Optional[Any] = None,
) -> dict:
    positions = list_positions(
        include_closed=True,
        only_closed=True,
        ticker_contains=ticker_contains,
        underlying_contains=underlying_contains,
        strategy_tag=strategy_tag,
        trade_type=trade_type,
        is_simulated=is_simulated,
        conn=conn,
    )

    closed_rows: list[dict] = []
    for pos in positions:
        exit_date = (pos.get("exit_date") or "").strip()
        realized_pl = pos.get("realized_pl")
        if not exit_date or realized_pl is None:
            continue
        try:
            exit_dt = dt.date.fromisoformat(exit_date)
        except ValueError:
            continue
        gross_value = round(float(realized_pl), 2)
        fees_value = round(float(pos.get("fees") or 0.0), 2)
        net_value = round(float(pos.get("pl") if pos.get("pl") is not None else gross_value - fees_value), 2)
        closed_rows.append(
            {
                "id": pos.get("id"),
                "ticker": pos.get("ticker"),
                "underlying": pos.get("underlying"),
                "trade_type": pos.get("trade_type"),
                "strategy_tag": pos.get("strategy_tag"),
                "side": pos.get("side"),
                "qty": int(pos.get("qty") or 0),
                "exit_date": exit_date,
                "exit_reason": pos.get("exit_reason"),
                "realized_pl": gross_value,
                "gross_result": gross_value,
                "fees": fees_value,
                "net_result": net_value,
                "irrf": round(float(pos.get("irrf") or 0.0), 2),
                "year": int(exit_dt.year),
                "month": int(exit_dt.month),
                "period": f"{exit_dt.year:04d}-{exit_dt.month:02d}",
            }
        )

    closed_rows.sort(key=lambda item: (item["exit_date"], int(item["id"] or 0)), reverse=True)
    available_years = sorted({int(item["year"]) for item in closed_rows}, reverse=True)

    normalized_year = selected_year if selected_year in available_years else None
    if normalized_year is None and available_years:
        normalized_year = available_years[0]

    available_months = sorted(
        {int(item["month"]) for item in closed_rows if item["year"] == normalized_year}
    ) if normalized_year is not None else []

    normalized_month = (
        selected_month if selected_month in available_months else None
    )

    def _build_totals(rows: list[dict]) -> dict:
        total_gross = round(sum(float(item["gross_result"]) for item in rows), 2)
        total_fees = round(sum(float(item["fees"]) for item in rows), 2)
        total_net = round(sum(float(item["net_result"]) for item in rows), 2)
        total_profit = round(
            sum(float(item["net_result"]) for item in rows if float(item["net_result"]) > 0),
            2,
        )
        total_loss = round(
            sum(float(item["net_result"]) for item in rows if float(item["net_result"]) < 0),
            2,
        )
        return {
            "count": len(rows),
            "total_gross": total_gross,
            "total_fees": total_fees,
            "total_net": total_net,
            "total_profit": total_profit,
            "total_loss": total_loss,
            "profit_count": sum(1 for item in rows if float(item["net_result"]) > 0),
            "loss_count": sum(1 for item in rows if float(item["net_result"]) < 0),
            "breakeven_count": sum(1 for item in rows if float(item["net_result"]) == 0),
        }

    monthly_index: dict[tuple[int, int], list[dict]] = {}
    yearly_index: dict[int, list[dict]] = {}
    for row in closed_rows:
        yearly_index.setdefault(int(row["year"]), []).append(row)
        monthly_index.setdefault((int(row["year"]), int(row["month"])), []).append(row)

    by_year = []
    for year in sorted(yearly_index.keys(), reverse=True):
        totals = _build_totals(yearly_index[year])
        by_year.append({"year": year, **totals})

    by_month = []
    for year, month in sorted(monthly_index.keys(), reverse=True):
        totals = _build_totals(monthly_index[(year, month)])
        by_month.append(
            {
                "year": year,
                "month": month,
                "period": f"{year:04d}-{month:02d}",
                "month_label": f"{month:02d}/{year:04d}",
                **totals,
            }
        )

    filtered_rows = closed_rows
    if normalized_year is not None:
        filtered_rows = [row for row in filtered_rows if int(row["year"]) == normalized_year]
    if normalized_month is not None:
        filtered_rows = [row for row in filtered_rows if int(row["month"]) == normalized_month]

    return {
        "available_years": available_years,
        "available_months": available_months,
        "selected_year": normalized_year,
        "selected_month": normalized_month,
        "overall_totals": _build_totals(closed_rows),
        "period_totals": _build_totals(filtered_rows),
        "by_year": by_year,
        "by_month": by_month,
        "period_positions": filtered_rows,
    }


def _row_to_dict(row: Any) -> dict:
    def parse_decimal(value: object) -> Optional[float]:
        parsed = parse_ptbr_number(value)
        if parsed is None:
            return None
        try:
            return float(parsed)
        except (TypeError, ValueError):
            return None

    def parse_int(value: Optional[str]) -> Optional[int]:
        if value is None:
            return None
        try:
            return int(str(value).strip())
        except ValueError:
            return None

    entry_price = float(row["entry_price"])
    qty = int(row["qty"])
    fees = float(row["fees"] or 0.0)
    partial_qty = int(row["partial_qty"] or 0) if "partial_qty" in row.keys() else 0
    partial_price = parse_decimal(row["partial_price"]) if "partial_price" in row.keys() else None
    partial_date = row["partial_date"] if "partial_date" in row.keys() else None
    exit_reason = row["exit_reason"] if "exit_reason" in row.keys() else None
    last_price = parse_decimal(row["last_price_raw"])
    status = (row["status"] or "").strip().lower()
    is_closed = status == "closed"
    open_qty_raw = max(qty - partial_qty, 0)
    open_qty = 0 if is_closed else open_qty_raw
    exit_price = parse_decimal(row["exit_price"]) if "exit_price" in row.keys() else None

    is_sim_raw = 0
    if "is_simulated" in row.keys():
        try:
            is_sim_raw = int(row["is_simulated"] or 0)
        except (TypeError, ValueError):
            is_sim_raw = 0

    raw_side = row["side"] if "side" in row.keys() else None
    side = _normalize_side(raw_side)
    if (raw_side is None or str(raw_side).strip() == ""):
        try:
            strat = (row["strategy_tag"] or "").strip().lower()
            ticker = (row["ticker"] or "").strip().upper()
            underlying = (row["underlying"] or "").strip().upper()
            if strat in {"cash_put", "covered_call"} and ticker and underlying and ticker != underlying:
                side = "short"
        except Exception:
            pass
    direction = -1 if side == "short" else 1

    def _calc_pl(price: float, qty_val: int) -> float:
        return direction * (float(price) - float(entry_price)) * int(qty_val)

    realized_pl = None
    if partial_qty and partial_price is not None:
        realized_pl = _calc_pl(partial_price, partial_qty)
    if is_closed and exit_price is not None and open_qty_raw > 0:
        realized_pl = (realized_pl or 0.0) + _calc_pl(exit_price, open_qty_raw)

    pl_open = None
    if not is_closed and last_price is not None and entry_price and open_qty > 0:
        pl_open = _calc_pl(last_price, open_qty)

    pl = None
    if realized_pl is not None or pl_open is not None:
        pl = (realized_pl or 0.0) + (pl_open or 0.0) - fees

    pl_pct = None
    if pl is not None and entry_price and qty > 0:
        invested = entry_price * qty
        pl_pct = (pl / invested) * 100.0

    breakeven = None
    if open_qty > 0:
        # preço tal que PL total (realizado + aberto - fees) = 0
        numerator = (realized_pl or 0.0) - fees
        breakeven = entry_price - (direction * (numerator / open_qty))

    underlying_price = None
    extrinsic_pct_spot = None
    pct_2x = None
    last_strike = None
    if "last_underlying_price" in row.keys():
        underlying_price = parse_decimal(row["last_underlying_price"])
    if "last_extrinsic_pct_spot" in row.keys():
        extrinsic_pct_spot = parse_decimal(row["last_extrinsic_pct_spot"])
    if "last_pct_2x" in row.keys():
        pct_2x = parse_decimal(row["last_pct_2x"])
    if "last_strike" in row.keys():
        last_strike = parse_decimal(row["last_strike"])

    return {
        "id": row["id"],
        "ticker": row["ticker"],
        "underlying": row["underlying"],
        "is_option": infer_option_type(row["ticker"]) in {"CALL", "PUT"},
        "trade_date": row["trade_date"],
        "qty": qty,
        "open_qty": open_qty,
        "entry_price": entry_price,
        "fees": fees,
        "status": row["status"],
        "side": side,
        "exit_date": row["exit_date"] if "exit_date" in row.keys() else None,
        "exit_price": exit_price,
        "notes": row["notes"] or "",
        "last_snapshot_date": row["last_snapshot_date"],
        "last_price": last_price,
        "pl": pl,
        "pl_pct": pl_pct,
        "score_total": parse_decimal(row["last_score_total"]),
        "trend_flag": row["last_trend_flag"],
        "vencimento": row["last_vencimento"],
        "dias_uteis": parse_int(row["last_dias_uteis"]),
        "partial_qty": partial_qty,
        "partial_price": partial_price,
        "partial_date": partial_date,
        "exit_reason": exit_reason,
        "realized_pl": realized_pl,
        "breakeven_price": breakeven,
        "trade_type": row["trade_type"],
        "irrf": row["irrf"] if "irrf" in row.keys() else None,
        "is_simulated": bool(is_sim_raw),
        "parent_position_id": row["parent_position_id"] if "parent_position_id" in row.keys() else None,
        "underlying_price": underlying_price,
        "extrinsic_pct_spot": extrinsic_pct_spot,
        "pct_2x": pct_2x,
        "strike": last_strike,
        "strategy_tag": row["strategy_tag"] if "strategy_tag" in row.keys() else None,
    }


__all__ = [
    "add_position",
    "delete_position",
    "close_position",
    "get_position",
    "list_positions",
    "summarize_realized_positions",
    "update_position",
]
