from __future__ import annotations

import re
from typing import Any, Iterable, List, Mapping, Optional

from .config import (
    get_postgres_schema,
)
from .db_health import resolve_postgres_target
from .utils import infer_option_type, parse_ptbr_number


class _PgResult:
    def __init__(
        self,
        rows: Optional[list[Mapping[str, Any]]] = None,
        *,
        rowcount: int = 0,
    ) -> None:
        self._rows = list(rows or [])
        self.rowcount = int(rowcount or 0)
        self.lastrowid = None

    def fetchone(self):
        if not self._rows:
            return None
        return self._rows[0]

    def fetchall(self):
        return list(self._rows)


class _DbConn:
    def __init__(
        self,
        *,
        backend: str,
        raw_conn: Any,
        pg_row_factory: Any = None,
    ) -> None:
        self.backend = backend
        self._raw_conn = raw_conn
        self._pg_row_factory = pg_row_factory

    def execute(self, query: str, params: Iterable[object] = ()):
        query_pg = query.replace("%", "%%").replace("?", "%s")
        with self._raw_conn.cursor(row_factory=self._pg_row_factory) as cur:
            cur.execute(query_pg, tuple(params))
            rowcount = int(cur.rowcount or 0)
            if cur.description is None:
                return _PgResult([], rowcount=rowcount)
            rows = cur.fetchall()
            return _PgResult(rows, rowcount=rowcount)

    def commit(self) -> None:
        self._raw_conn.commit()

    def close(self) -> None:
        self._raw_conn.close()

    def rollback(self) -> None:
        self._raw_conn.rollback()

    @property
    def in_transaction(self) -> bool:
        info = getattr(self._raw_conn, "info", None)
        status = getattr(info, "transaction_status", None)
        if status is None:
            return False
        status_name = str(getattr(status, "name", status)).upper()
        return status_name not in {"IDLE", "UNKNOWN"}


def _first_col(row: Any) -> Any:
    if row is None:
        return None
    if isinstance(row, Mapping):
        values = list(row.values())
        return values[0] if values else None
    try:
        return row[0]
    except Exception:
        return None


def _quote_ident(value: str) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def _connect_postgres(*, ensure_schema: bool = False) -> _DbConn:
    target, errors = resolve_postgres_target()
    if target is None:
        reasons = "; ".join(errors) if errors else "configuração ausente"
        raise RuntimeError(f"PostgreSQL não configurado: {reasons}")
    try:
        import psycopg
        from psycopg.rows import dict_row
    except Exception as exc:
        raise RuntimeError(
            "Driver psycopg não encontrado. Instale com: uv add psycopg[binary]"
        ) from exc

    schema = get_postgres_schema()
    raw_conn = psycopg.connect(target.dsn, row_factory=dict_row)
    with raw_conn.cursor() as cur:
        cur.execute(f"CREATE SCHEMA IF NOT EXISTS {_quote_ident(schema)}")
        cur.execute(f"SET search_path TO {_quote_ident(schema)}")
    conn = _DbConn(backend="postgres", raw_conn=raw_conn, pg_row_factory=dict_row)
    if ensure_schema:
        _ensure_tables(conn, commit=True)
    return conn


def _connect(*, ensure_schema: bool = False) -> _DbConn:
    return _connect_postgres(ensure_schema=ensure_schema)


def _wrap_existing_conn(conn: Any) -> _DbConn:
    if isinstance(conn, _DbConn):
        return conn
    return _DbConn(backend="postgres", raw_conn=conn)


def _resolve_conn(
    conn: Optional[Any],
    *,
    ensure_schema: bool = False,
) -> tuple[_DbConn, bool]:
    if conn is None:
        return _connect(ensure_schema=ensure_schema), True
    db = _wrap_existing_conn(conn)
    if ensure_schema:
        _ensure_tables(db, commit=not db.in_transaction)
    return db, False


def _ensure_tables(conn: _DbConn, *, commit: bool) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS positions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ticker TEXT NOT NULL,
            underlying TEXT NOT NULL,
            trade_date TEXT NOT NULL,
            qty INTEGER NOT NULL,
            entry_price DOUBLE PRECISION NOT NULL,
            fees DOUBLE PRECISION DEFAULT 0,
            trade_type TEXT DEFAULT 'swing',
            side TEXT DEFAULT 'long',
            irrf DOUBLE PRECISION,
            status TEXT NOT NULL DEFAULT 'open',
            exit_date TEXT,
            exit_price DOUBLE PRECISION,
            notes TEXT,
            partial_date TEXT,
            partial_price DOUBLE PRECISION,
            partial_qty INTEGER,
            exit_reason TEXT,
            is_simulated INTEGER DEFAULT 0,
            parent_position_id BIGINT,
            strategy_tag TEXT
        )
        """
    )

    _ensure_position_columns(conn)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_positions_ticker ON positions (ticker)")
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_positions_status_trade_date ON positions (status, trade_date DESC, id DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_positions_strategy_status ON positions (strategy_tag, status)"
    )
    _migrate_strategy_sides(conn)
    _migrate_stock_underlying_defaults(conn)
    if commit:
        conn.commit()


def _ensure_position_columns(conn: _DbConn) -> None:
    rows = conn.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'positions'
        """
    ).fetchall()
    existing = {str(r["column_name"]) for r in rows}
    columns = {
        "partial_date": "TEXT",
        "partial_price": "DOUBLE PRECISION",
        "partial_qty": "INTEGER",
        "exit_reason": "TEXT",
        "trade_type": "TEXT",
        "side": "TEXT DEFAULT 'long'",
        "irrf": "DOUBLE PRECISION",
        "is_simulated": "INTEGER DEFAULT 0",
        "parent_position_id": "BIGINT",
        "strategy_tag": "TEXT",
    }
    for col, col_type in columns.items():
        if col not in existing:
            conn.execute(
                f'ALTER TABLE positions ADD COLUMN IF NOT EXISTS "{col}" {col_type}'
            )


def _migrate_strategy_sides(conn: _DbConn) -> None:
    """Marca como vendidas posições de estratégia short (cash_put/covered_call)."""
    try:
        conn.execute(
            """
            UPDATE positions
            SET side = 'short'
            WHERE LOWER(COALESCE(side, '')) != 'short'
              AND strategy_tag IN ('cash_put', 'covered_call')
              AND UPPER(COALESCE(ticker, '')) != UPPER(COALESCE(underlying, ''))
            """
        )
    except Exception:
        # Evita quebrar o fluxo em bancos antigos/parciais.
        return


def _migrate_stock_underlying_defaults(conn: _DbConn) -> None:
    """Preenche underlying vazio para ações em estoque, usando o próprio ticker."""

    try:
        conn.execute(
            """
            UPDATE positions
            SET underlying = UPPER(TRIM(ticker))
            WHERE COALESCE(TRIM(underlying), '') = ''
              AND LOWER(COALESCE(side, 'long')) != 'short'
              AND LOWER(COALESCE(strategy_tag, '')) NOT IN ('cash_put', 'covered_call', 'ranking')
              AND UPPER(TRIM(ticker)) ~ '^[A-Z]{4}[0-9]{1,2}$'
            """
        )
    except Exception:
        # Evita quebrar o fluxo em bancos antigos/parciais.
        return


def _normalize_ticker(value: str) -> str:
    return (value or "").strip().upper()


def _normalize_side(value: Optional[str]) -> str:
    text = (value or "").strip().lower()
    if text in {"short", "vendida", "vendido", "v"}:
        return "short"
    return "long"


def _looks_like_stock_ticker(value: str) -> bool:
    return bool(re.fullmatch(r"[A-Z]{4}[0-9]{1,2}", (value or "").strip().upper()))


def _table_exists(conn: _DbConn, table_name: str) -> bool:
    row = conn.execute("SELECT to_regclass(?)", (table_name,)).fetchone()
    return _first_col(row) is not None


def _has_option_snapshots_table(conn: _DbConn) -> bool:
    return _table_exists(conn, "option_snapshots")


def _snapshot_subquery_sql(has_snapshot_table: bool) -> str:
    if has_snapshot_table:
        return """
            SELECT os1.*
            FROM option_snapshots os1
            INNER JOIN (
                SELECT ticker, MAX(snapshot_date) AS snapshot_date
                FROM option_snapshots
                GROUP BY ticker
            ) latest
            ON os1.ticker = latest.ticker AND os1.snapshot_date = latest.snapshot_date
        """

    # Banco recém-criado (sem snapshots): mantém o JOIN compatível retornando NULLs.
    return """
        SELECT
            NULL AS ticker,
            NULL AS snapshot_date,
            NULL AS "ultimo",
            NULL AS "score_total",
            NULL AS "trend_flag",
            NULL AS "vencimento",
            NULL AS "dias_uteis",
            NULL AS "underlying_price",
            NULL AS "extrinsic_pct_spot",
            NULL AS "%_Alta_p_2x",
            NULL AS "strike"
        WHERE 1 = 0
    """


def add_position(
    *,
    ticker: str,
    underlying: str,
    trade_date: str,
    qty: int,
    entry_price: float,
    fees: float = 0.0,
    trade_type: str = "swing",
    side: str = "long",
    irrf: Optional[float] = None,
    notes: Optional[str] = None,
    partial_date: Optional[str] = None,
    partial_price: Optional[float] = None,
    partial_qty: Optional[int] = None,
    exit_reason: Optional[str] = None,
    is_simulated: bool = False,
    parent_position_id: Optional[int] = None,
    strategy_tag: Optional[str] = None,
    conn: Optional[Any] = None,
) -> int:
    db, owns_conn = _resolve_conn(conn, ensure_schema=True)
    normalized_ticker = _normalize_ticker(ticker)
    normalized_underlying = _normalize_ticker(underlying)
    if not normalized_underlying and _looks_like_stock_ticker(normalized_ticker):
        normalized_underlying = normalized_ticker
    params = (
        normalized_ticker,
        normalized_underlying,
        trade_date,
        int(qty),
        float(entry_price),
        float(fees or 0.0),
        trade_type,
        _normalize_side(side),
        float(irrf) if irrf is not None else None,
        notes,
        partial_date,
        float(partial_price) if partial_price is not None else None,
        int(partial_qty) if partial_qty is not None else None,
        exit_reason,
        1 if is_simulated else 0,
        int(parent_position_id) if parent_position_id is not None else None,
        strategy_tag or None,
    )
    try:
        if db.backend == "postgres":
            row = db.execute(
                """
                INSERT INTO positions (
                    ticker,
                    underlying,
                    trade_date,
                    qty,
                    entry_price,
                    fees,
                    trade_type,
                    side,
                    irrf,
                    notes,
                    partial_date,
                    partial_price,
                    partial_qty,
                    exit_reason,
                    is_simulated,
                    parent_position_id,
                    strategy_tag
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """,
                params,
            ).fetchone()
            pos_id = _first_col(row)
        else:
            cur = db.execute(
                """
                INSERT INTO positions (
                    ticker,
                    underlying,
                    trade_date,
                    qty,
                    entry_price,
                    fees,
                    trade_type,
                    side,
                    irrf,
                    notes,
                    partial_date,
                    partial_price,
                    partial_qty,
                    exit_reason,
                    is_simulated,
                    parent_position_id,
                    strategy_tag
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                params,
            )
            pos_id = getattr(cur, "lastrowid", None)
        if pos_id is None:
            raise RuntimeError("Falha ao obter id da posição inserida.")
        if owns_conn:
            db.commit()
        return int(pos_id)
    finally:
        if owns_conn:
            db.close()


def close_position(
    *,
    position_id: int,
    exit_date: str,
    exit_price: float,
    exit_reason: Optional[str] = None,
    conn: Optional[Any] = None,
) -> None:
    db, owns_conn = _resolve_conn(conn, ensure_schema=True)
    cur = db.execute(
        """
        UPDATE positions
        SET status = 'closed',
            exit_date = ?,
            exit_price = ?,
            exit_reason = COALESCE(?, exit_reason)
        WHERE id = ? AND status = 'open'
        """,
        (exit_date, float(exit_price), exit_reason, int(position_id)),
    )
    if cur.rowcount == 0:
        if owns_conn:
            db.close()
        raise ValueError(f"Posição {position_id} não encontrada ou já fechada.")
    if owns_conn:
        db.commit()
        db.close()


def update_position(
    *,
    position_id: int,
    ticker: Optional[str] = None,
    underlying: Optional[str] = None,
    trade_date: Optional[str] = None,
    qty: Optional[int] = None,
    entry_price: Optional[float] = None,
    fees: Optional[float] = None,
    status: Optional[str] = None,
    exit_date: Optional[str] = None,
    exit_price: Optional[float] = None,
    notes: Optional[str] = None,
    partial_date: Optional[str] = None,
    partial_price: Optional[float] = None,
    partial_qty: Optional[int] = None,
    exit_reason: Optional[str] = None,
    trade_type: Optional[str] = None,
    side: Optional[str] = None,
    irrf: Optional[float] = None,
    is_simulated: Optional[bool] = None,
    parent_position_id: Optional[int] = None,
    strategy_tag: Optional[str] = None,
    conn: Optional[Any] = None,
) -> None:
    fields = []
    params = []
    if ticker is not None:
        fields.append("ticker = ?")
        params.append(_normalize_ticker(ticker))
    if underlying is not None:
        fields.append("underlying = ?")
        params.append(_normalize_ticker(underlying))
    if trade_date is not None:
        fields.append("trade_date = ?")
        params.append(trade_date)
    if qty is not None:
        fields.append("qty = ?")
        params.append(int(qty))
    if entry_price is not None:
        fields.append("entry_price = ?")
        params.append(float(entry_price))
    if fees is not None:
        fields.append("fees = ?")
        params.append(float(fees))
    if status is not None:
        fields.append("status = ?")
        params.append(status)
    if exit_date is not None:
        fields.append("exit_date = ?")
        params.append(exit_date)
    if exit_price is not None:
        fields.append("exit_price = ?")
        params.append(float(exit_price))
    if notes is not None:
        fields.append("notes = ?")
        params.append(notes)
    if partial_date is not None:
        fields.append("partial_date = ?")
        params.append(partial_date)
    if partial_price is not None:
        fields.append("partial_price = ?")
        params.append(float(partial_price))
    if partial_qty is not None:
        fields.append("partial_qty = ?")
        params.append(int(partial_qty))
    if exit_reason is not None:
        fields.append("exit_reason = ?")
        params.append(exit_reason)
    if trade_type is not None:
        fields.append("trade_type = ?")
        params.append(trade_type)
    if side is not None:
        fields.append("side = ?")
        params.append(_normalize_side(side))
    if irrf is not None:
        fields.append("irrf = ?")
        params.append(float(irrf))
    if is_simulated is not None:
        fields.append("is_simulated = ?")
        params.append(1 if is_simulated else 0)
    if parent_position_id is not None:
        fields.append("parent_position_id = ?")
        params.append(int(parent_position_id))
    if strategy_tag is not None:
        fields.append("strategy_tag = ?")
        params.append(strategy_tag)
    if not fields:
        return

    params.append(int(position_id))
    db, owns_conn = _resolve_conn(conn, ensure_schema=True)
    cur = db.execute(f"UPDATE positions SET {', '.join(fields)} WHERE id = ?", params)
    if cur.rowcount == 0:
        if owns_conn:
            db.close()
        raise ValueError(f"Posição {position_id} não encontrada.")
    if owns_conn:
        db.commit()
        db.close()


def delete_position(*, position_id: int, conn: Optional[Any] = None) -> None:
    db, owns_conn = _resolve_conn(conn, ensure_schema=True)
    db.execute("DELETE FROM positions WHERE id = ?", (int(position_id),))
    if owns_conn:
        db.commit()
        db.close()


def get_position(position_id: int, *, conn: Optional[Any] = None) -> Optional[dict]:
    db, owns_conn = _resolve_conn(conn)
    try:
        if not _table_exists(db, "positions"):
            return None
        has_snapshots = _has_option_snapshots_table(db)
        if db.backend == "postgres":
            if has_snapshots:
                query = """
                    SELECT
                        p.*,
                        snap.snapshot_date AS last_snapshot_date,
                        snap."ultimo" AS last_price_raw,
                        snap."score_total" AS last_score_total,
                        snap."trend_flag" AS last_trend_flag,
                        snap."vencimento" AS last_vencimento,
                        snap."dias_uteis" AS last_dias_uteis,
                        snap."underlying_price" AS last_underlying_price,
                        snap."extrinsic_pct_spot" AS last_extrinsic_pct_spot,
                        snap."%_Alta_p_2x" AS last_pct_2x,
                        snap."strike" AS last_strike
                    FROM positions p
                    LEFT JOIN LATERAL (
                        SELECT
                            os.snapshot_date,
                            os."ultimo",
                            os."score_total",
                            os."trend_flag",
                            os."vencimento",
                            os."dias_uteis",
                            os."underlying_price",
                            os."extrinsic_pct_spot",
                            os."%_Alta_p_2x",
                            os."strike"
                        FROM option_snapshots os
                        WHERE os.ticker = p.ticker
                        ORDER BY os.snapshot_date DESC
                        LIMIT 1
                    ) AS snap ON TRUE
                    WHERE p.id = ?
                """
            else:
                query = """
                    SELECT
                        p.*,
                        NULL AS last_snapshot_date,
                        NULL AS last_price_raw,
                        NULL AS last_score_total,
                        NULL AS last_trend_flag,
                        NULL AS last_vencimento,
                        NULL AS last_dias_uteis,
                        NULL AS last_underlying_price,
                        NULL AS last_extrinsic_pct_spot,
                        NULL AS last_pct_2x,
                        NULL AS last_strike
                    FROM positions p
                    WHERE p.id = ?
                """
        else:
            snap_subquery = _snapshot_subquery_sql(has_snapshots)
            query = f"""
                SELECT
                    p.*,
                    snap.snapshot_date AS last_snapshot_date,
                    snap."ultimo" AS last_price_raw,
                    snap."score_total" AS last_score_total,
                    snap."trend_flag" AS last_trend_flag,
                    snap."vencimento" AS last_vencimento,
                    snap."dias_uteis" AS last_dias_uteis,
                    snap."underlying_price" AS last_underlying_price,
                    snap."extrinsic_pct_spot" AS last_extrinsic_pct_spot,
                    snap."%_Alta_p_2x" AS last_pct_2x,
                    snap."strike" AS last_strike
                FROM positions p
                LEFT JOIN (
                    {snap_subquery}
                ) AS snap ON snap.ticker = p.ticker
                WHERE p.id = ?
            """
        row = db.execute(query, (int(position_id),)).fetchone()
        return _row_to_dict(row) if row else None
    finally:
        if owns_conn:
            db.close()


def list_positions(
    *,
    include_closed: bool = False,
    ticker: Optional[str] = None,
    only_closed: bool = False,
    ticker_contains: Optional[str] = None,
    underlying_contains: Optional[str] = None,
    strategy_tag: Optional[str] = None,
    trade_type: Optional[str] = None,
    is_simulated: Optional[bool] = None,
    conn: Optional[Any] = None,
) -> List[dict]:
    db, owns_conn = _resolve_conn(conn)
    if not _table_exists(db, "positions"):
        if owns_conn:
            db.close()
        return []
    where: List[str] = []
    params: List[object] = []
    if only_closed:
        where.append("p.status = 'closed'")
    elif not include_closed:
        where.append("p.status = 'open'")
    if ticker:
        where.append("p.ticker = ?")
        params.append(_normalize_ticker(ticker))
    if ticker_contains:
        where.append("p.ticker LIKE ?")
        params.append(f"%{_normalize_ticker(ticker_contains)}%")
    if underlying_contains:
        where.append("p.underlying LIKE ?")
        params.append(f"%{_normalize_ticker(underlying_contains)}%")
    if trade_type:
        where.append("p.trade_type = ?")
        params.append((trade_type or "").strip().lower())
    if strategy_tag:
        if strategy_tag == "__none__":
            where.append("COALESCE(p.strategy_tag, '') = ''")
        else:
            where.append("p.strategy_tag = ?")
            params.append((strategy_tag or "").strip())
    if is_simulated is not None:
        where.append("COALESCE(p.is_simulated, 0) = ?")
        params.append(1 if is_simulated else 0)
    where_clause = f"WHERE {' AND '.join(where)}" if where else ""
    has_snapshots = _has_option_snapshots_table(db)
    if db.backend == "postgres":
        if has_snapshots:
            query = f"""
                SELECT
                    p.*,
                    snap.snapshot_date AS last_snapshot_date,
                    snap."ultimo" AS last_price_raw,
                    snap."score_total" AS last_score_total,
                    snap."trend_flag" AS last_trend_flag,
                    snap."vencimento" AS last_vencimento,
                    snap."dias_uteis" AS last_dias_uteis,
                    snap."underlying_price" AS last_underlying_price,
                    snap."extrinsic_pct_spot" AS last_extrinsic_pct_spot,
                    snap."%_Alta_p_2x" AS last_pct_2x,
                    snap."strike" AS last_strike
                FROM positions p
                LEFT JOIN LATERAL (
                    SELECT
                        os.snapshot_date,
                        os."ultimo",
                        os."score_total",
                        os."trend_flag",
                        os."vencimento",
                        os."dias_uteis",
                        os."underlying_price",
                        os."extrinsic_pct_spot",
                        os."%_Alta_p_2x",
                        os."strike"
                    FROM option_snapshots os
                    WHERE os.ticker = p.ticker
                    ORDER BY os.snapshot_date DESC
                    LIMIT 1
                ) AS snap ON TRUE
                {where_clause}
                ORDER BY p.trade_date DESC, p.id DESC
            """
        else:
            query = f"""
                SELECT
                    p.*,
                    NULL AS last_snapshot_date,
                    NULL AS last_price_raw,
                    NULL AS last_score_total,
                    NULL AS last_trend_flag,
                    NULL AS last_vencimento,
                    NULL AS last_dias_uteis,
                    NULL AS last_underlying_price,
                    NULL AS last_extrinsic_pct_spot,
                    NULL AS last_pct_2x,
                    NULL AS last_strike
                FROM positions p
                {where_clause}
                ORDER BY p.trade_date DESC, p.id DESC
            """
    else:
        snap_subquery = _snapshot_subquery_sql(has_snapshots)
        query = f"""
            SELECT
                p.*,
                snap.snapshot_date AS last_snapshot_date,
                snap."ultimo" AS last_price_raw,
                snap."score_total" AS last_score_total,
                snap."trend_flag" AS last_trend_flag,
                snap."vencimento" AS last_vencimento,
                snap."dias_uteis" AS last_dias_uteis,
                snap."underlying_price" AS last_underlying_price,
                snap."extrinsic_pct_spot" AS last_extrinsic_pct_spot,
                snap."%_Alta_p_2x" AS last_pct_2x,
                snap."strike" AS last_strike
            FROM positions p
            LEFT JOIN (
                {snap_subquery}
            ) AS snap ON snap.ticker = p.ticker
            {where_clause}
            ORDER BY p.trade_date DESC, p.id DESC
        """
    rows = db.execute(query, params).fetchall()
    if owns_conn:
        db.close()
    return [_row_to_dict(row) for row in rows]


def _row_to_dict(row: Any) -> dict:
    def parse_decimal(value: object) -> Optional[float]:
        parsed = parse_ptbr_number(value)
        if parsed is None:
            return None
        try:
            return float(parsed)
        except (TypeError, ValueError):
            return None

    def parse_int(value: Optional[str]) -> Optional[int]:
        if value is None:
            return None
        try:
            return int(str(value).strip())
        except ValueError:
            return None

    entry_price = float(row["entry_price"])
    qty = int(row["qty"])
    fees = float(row["fees"] or 0.0)
    partial_qty = int(row["partial_qty"] or 0) if "partial_qty" in row.keys() else 0
    partial_price = parse_decimal(row["partial_price"]) if "partial_price" in row.keys() else None
    partial_date = row["partial_date"] if "partial_date" in row.keys() else None
    exit_reason = row["exit_reason"] if "exit_reason" in row.keys() else None
    last_price = parse_decimal(row["last_price_raw"])
    status = (row["status"] or "").strip().lower()
    is_closed = status == "closed"
    open_qty_raw = max(qty - partial_qty, 0)
    open_qty = 0 if is_closed else open_qty_raw
    exit_price = parse_decimal(row["exit_price"]) if "exit_price" in row.keys() else None

    is_sim_raw = 0
    if "is_simulated" in row.keys():
        try:
            is_sim_raw = int(row["is_simulated"] or 0)
        except (TypeError, ValueError):
            is_sim_raw = 0

    raw_side = row["side"] if "side" in row.keys() else None
    side = _normalize_side(raw_side)
    if (raw_side is None or str(raw_side).strip() == ""):
        try:
            strat = (row["strategy_tag"] or "").strip().lower()
            ticker = (row["ticker"] or "").strip().upper()
            underlying = (row["underlying"] or "").strip().upper()
            if strat in {"cash_put", "covered_call"} and ticker and underlying and ticker != underlying:
                side = "short"
        except Exception:
            pass
    direction = -1 if side == "short" else 1

    def _calc_pl(price: float, qty_val: int) -> float:
        return direction * (float(price) - float(entry_price)) * int(qty_val)

    realized_pl = None
    if partial_qty and partial_price is not None:
        realized_pl = _calc_pl(partial_price, partial_qty)
    if is_closed and exit_price is not None and open_qty_raw > 0:
        realized_pl = (realized_pl or 0.0) + _calc_pl(exit_price, open_qty_raw)

    pl_open = None
    if not is_closed and last_price is not None and entry_price and open_qty > 0:
        pl_open = _calc_pl(last_price, open_qty)

    pl = None
    if realized_pl is not None or pl_open is not None:
        pl = (realized_pl or 0.0) + (pl_open or 0.0) - fees

    pl_pct = None
    if pl is not None and entry_price and qty > 0:
        invested = entry_price * qty
        pl_pct = (pl / invested) * 100.0

    breakeven = None
    if open_qty > 0:
        # preço tal que PL total (realizado + aberto - fees) = 0
        numerator = (realized_pl or 0.0) - fees
        breakeven = entry_price - (direction * (numerator / open_qty))

    underlying_price = None
    extrinsic_pct_spot = None
    pct_2x = None
    last_strike = None
    if "last_underlying_price" in row.keys():
        underlying_price = parse_decimal(row["last_underlying_price"])
    if "last_extrinsic_pct_spot" in row.keys():
        extrinsic_pct_spot = parse_decimal(row["last_extrinsic_pct_spot"])
    if "last_pct_2x" in row.keys():
        pct_2x = parse_decimal(row["last_pct_2x"])
    if "last_strike" in row.keys():
        last_strike = parse_decimal(row["last_strike"])

    return {
        "id": row["id"],
        "ticker": row["ticker"],
        "underlying": row["underlying"],
        "is_option": infer_option_type(row["ticker"]) in {"CALL", "PUT"},
        "trade_date": row["trade_date"],
        "qty": qty,
        "open_qty": open_qty,
        "entry_price": entry_price,
        "fees": fees,
        "status": row["status"],
        "side": side,
        "exit_date": row["exit_date"] if "exit_date" in row.keys() else None,
        "exit_price": exit_price,
        "notes": row["notes"] or "",
        "last_snapshot_date": row["last_snapshot_date"],
        "last_price": last_price,
        "pl": pl,
        "pl_pct": pl_pct,
        "score_total": parse_decimal(row["last_score_total"]),
        "trend_flag": row["last_trend_flag"],
        "vencimento": row["last_vencimento"],
        "dias_uteis": parse_int(row["last_dias_uteis"]),
        "partial_qty": partial_qty,
        "partial_price": partial_price,
        "partial_date": partial_date,
        "exit_reason": exit_reason,
        "realized_pl": realized_pl,
        "breakeven_price": breakeven,
        "trade_type": row["trade_type"],
        "irrf": row["irrf"],
        "is_simulated": bool(is_sim_raw),
        "parent_position_id": row["parent_position_id"] if "parent_position_id" in row.keys() else None,
        "underlying_price": underlying_price,
        "extrinsic_pct_spot": extrinsic_pct_spot,
        "pct_2x": pct_2x,
        "strike": last_strike,
        "strategy_tag": row["strategy_tag"] if "strategy_tag" in row.keys() else None,
    }


__all__ = [
    "add_position",
    "list_positions",
    "get_position",
    "update_position",
    "close_position",
    "delete_position",
]
