from __future__ import annotations

import datetime as dt
import math
import unicodedata
from collections import defaultdict
from typing import Any, Mapping, Sequence

from . import finance
from .db import db_transaction
from .portfolio import list_positions
from .utils import infer_option_type


LEG_TYPES = (
    "put_origin",
    "stock_acquisition",
    "covered_call",
    "stock_exit",
    "expense",
)
_OPTION_LEGS = {"put_origin", "covered_call"}


class WheelCycleError(ValueError):
    """Raised when a Wheel cycle would become financially ambiguous."""


def _text(value: Any) -> str:
    return str(value or "").strip()


def _upper(value: Any) -> str:
    return _text(value).upper()


def _int(value: Any, *, label: str) -> int:
    try:
        number = int(value)
    except (TypeError, ValueError) as exc:
        raise WheelCycleError(f"{label} invalida.") from exc
    if number <= 0:
        raise WheelCycleError(f"{label} precisa ser maior que zero.")
    return number


def _money(value: Any, *, label: str, allow_zero: bool = True) -> float:
    try:
        amount = float(str(value).strip().replace(",", "."))
    except (TypeError, ValueError) as exc:
        raise WheelCycleError(f"{label} invalido.") from exc
    if not math.isfinite(amount) or (not allow_zero and amount == 0):
        raise WheelCycleError(f"{label} invalido.")
    return round(amount, 2)


def _is_exercise(value: Any) -> bool:
    normalized = unicodedata.normalize("NFKD", _text(value)).encode("ascii", "ignore").decode()
    return "exerc" in normalized.lower()


def _date(value: Any, *, label: str) -> str:
    try:
        return dt.date.fromisoformat(_text(value)).isoformat()
    except ValueError as exc:
        raise WheelCycleError(f"{label} invalida. Use YYYY-MM-DD.") from exc


def ensure_wheel_cycle_schema(conn: Any) -> None:
    """Idempotent application migration for explicit Wheel-cycle relations."""

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS strategy_cycles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            underlying TEXT NOT NULL,
            is_simulated INTEGER NOT NULL DEFAULT 0 CHECK (is_simulated IN (0, 1)),
            status TEXT NOT NULL DEFAULT 'open'
                CHECK (status IN ('open', 'closed', 'requires_review')),
            opened_at TEXT NOT NULL,
            closed_at TEXT,
            origin_put_position_id BIGINT UNIQUE REFERENCES positions(id) ON DELETE RESTRICT,
            source_ref TEXT NOT NULL,
            notes TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS strategy_cycle_legs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cycle_id BIGINT NOT NULL REFERENCES strategy_cycles(id) ON DELETE CASCADE,
            position_id BIGINT REFERENCES positions(id) ON DELETE RESTRICT,
            leg_type TEXT NOT NULL CHECK (
                leg_type IN ('put_origin', 'stock_acquisition', 'covered_call', 'stock_exit', 'expense')
            ),
            quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
            amount_override DOUBLE PRECISION,
            source_ref TEXT NOT NULL DEFAULT '',
            notes TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE (cycle_id, position_id),
            CHECK (
                (leg_type = 'expense' AND position_id IS NULL AND quantity = 0 AND amount_override IS NOT NULL)
                OR (leg_type <> 'expense' AND position_id IS NOT NULL AND quantity > 0)
            )
        )
        """
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_strategy_cycles_mode_underlying ON strategy_cycles (is_simulated, underlying, opened_at DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_strategy_cycle_legs_position ON strategy_cycle_legs (position_id) WHERE position_id IS NOT NULL"
    )


def _fetch_cycle(conn: Any, cycle_id: int, *, lock: bool = False) -> Mapping[str, Any]:
    suffix = " FOR UPDATE" if lock else ""
    cycle = conn.execute(f"SELECT * FROM strategy_cycles WHERE id = %s{suffix}", (cycle_id,)).fetchone()
    if cycle is None:
        raise WheelCycleError("Ciclo Wheel nao encontrado.")
    return cycle


def _fetch_cycle_legs(conn: Any, cycle_id: int) -> list[dict[str, Any]]:
    rows = conn.execute(
        "SELECT * FROM strategy_cycle_legs WHERE cycle_id = %s ORDER BY id", (cycle_id,)
    ).fetchall()
    return [dict(row) for row in rows]


def _position_document_ref(position: Mapping[str, Any]) -> str:
    return _text(position.get("performance_source_ref")) or _text(position.get("notes"))


def _validate_position_for_leg(
    *, cycle: Mapping[str, Any], position: Mapping[str, Any], leg_type: str, quantity: int
) -> None:
    if _upper(position.get("underlying")) != _upper(cycle.get("underlying")):
        raise WheelCycleError("A posicao pertence a outro ativo-base.")
    if bool(position.get("is_simulated") or 0) != bool(cycle.get("is_simulated") or 0):
        raise WheelCycleError("Ciclo e posicao pertencem a modos diferentes.")
    position_qty = _int(position.get("qty"), label="Quantidade da posicao")
    if quantity > position_qty:
        raise WheelCycleError("A quantidade vinculada ultrapassa a quantidade da posicao.")

    option_type = infer_option_type(position.get("ticker"))
    strategy = _text(position.get("strategy_tag")).lower()
    if leg_type == "put_origin":
        if not (strategy == "cash_put" and option_type == "PUT" and _is_exercise(position.get("exit_reason"))):
            raise WheelCycleError("A origem do ciclo precisa ser uma PUT exercida de Cash-Covered Put.")
    elif leg_type == "stock_acquisition":
        if option_type is not None or _upper(position.get("ticker")) != _upper(cycle.get("underlying")):
            raise WheelCycleError("A aquisicao precisa apontar para um historico de acoes do ativo-base.")
    elif leg_type == "covered_call":
        if not (strategy == "covered_call" and option_type == "CALL"):
            raise WheelCycleError("Esta perna precisa apontar para uma CALL de Covered Call.")
    elif leg_type == "stock_exit":
        if option_type is not None or _upper(position.get("ticker")) != _upper(cycle.get("underlying")):
            raise WheelCycleError("A saida precisa apontar para uma venda de acoes do ativo-base.")
        if _text(position.get("status")).lower() != "closed" or not position.get("exit_price"):
            raise WheelCycleError("A saida de acoes precisa estar fechada com preco confirmado.")


def _validate_stock_quantities(
    *, cycle: Mapping[str, Any], legs: Sequence[Mapping[str, Any]]
) -> None:
    acquired = sum(int(leg.get("quantity") or 0) for leg in legs if leg.get("leg_type") == "stock_acquisition")
    exited = sum(int(leg.get("quantity") or 0) for leg in legs if leg.get("leg_type") == "stock_exit")
    if exited > acquired:
        raise WheelCycleError("A saida de acoes ultrapassa a quantidade adquirida no ciclo.")

    exercised_calls = 0
    for leg in legs:
        if leg.get("leg_type") != "covered_call":
            continue
        position = leg.get("position") or {}
        if _is_exercise(position.get("exit_reason")):
            exercised_calls += int(leg.get("quantity") or 0)
    if exercised_calls > acquired:
        raise WheelCycleError("CALL exercida consome mais acoes do que o ciclo possui.")


def _validate_prospective_leg(
    conn: Any,
    *,
    cycle: Mapping[str, Any],
    cycle_id: int,
    leg_type: str,
    position: Mapping[str, Any] | None,
    quantity: int,
) -> None:
    existing = _fetch_cycle_legs(conn, cycle_id)
    if leg_type == "put_origin" and any(leg["leg_type"] == "put_origin" for leg in existing):
        raise WheelCycleError("Um ciclo Wheel pode ter somente uma PUT de origem.")
    if position is None:
        return
    position_ids = [int(leg["position_id"]) for leg in existing if leg.get("position_id")]
    positions: dict[int, Mapping[str, Any]] = {int(position["id"]): position}
    if position_ids:
        rows = conn.execute("SELECT * FROM positions WHERE id = ANY(%s)", (position_ids,)).fetchall()
        positions.update({int(row["id"]): row for row in rows})
    prospective = [
        {
            **leg,
            "position": positions.get(int(leg["position_id"])) if leg.get("position_id") else None,
        }
        for leg in existing
    ]
    prospective.append({"leg_type": leg_type, "quantity": quantity, "position": position})
    _validate_stock_quantities(cycle=cycle, legs=prospective)


def _validate_stock_exit_parent(
    conn: Any, *, cycle_id: int, position: Mapping[str, Any], quantity: int
) -> None:
    """Require a linked exercise to be in the same cycle, while allowing direct sales."""

    parent_id = int(position.get("parent_position_id") or 0)
    if parent_id <= 0:
        return
    parent = conn.execute("SELECT * FROM positions WHERE id = %s", (parent_id,)).fetchone()
    if parent is None or infer_option_type(parent.get("ticker")) != "CALL" or not _is_exercise(parent.get("exit_reason")):
        return
    linked = conn.execute(
        "SELECT quantity FROM strategy_cycle_legs WHERE cycle_id = %s AND position_id = %s AND leg_type = 'covered_call'",
        (cycle_id, parent_id),
    ).fetchone()
    if linked is None:
        raise WheelCycleError("A saida por exercicio exige que a CALL correspondente esteja no mesmo ciclo.")
    if int(linked["quantity"] or 0) != quantity or _text(parent.get("exit_date")) != _text(position.get("exit_date")):
        raise WheelCycleError("A saida de acoes diverge da quantidade ou data da CALL exercida.")


def _refresh_cycle_status(conn: Any, cycle_id: int) -> None:
    cycle = _fetch_cycle(conn, cycle_id, lock=True)
    legs = _fetch_cycle_legs(conn, cycle_id)
    position_ids = [int(leg["position_id"]) for leg in legs if leg.get("position_id")]
    positions: dict[int, Mapping[str, Any]] = {}
    if position_ids:
        rows = conn.execute("SELECT * FROM positions WHERE id = ANY(%s)", (position_ids,)).fetchall()
        positions = {int(row["id"]): row for row in rows}
    enriched = [{**leg, "position": positions.get(int(leg["position_id"])) if leg.get("position_id") else None} for leg in legs]
    try:
        _validate_stock_quantities(cycle=cycle, legs=enriched)
        has_put = any(leg["leg_type"] == "put_origin" for leg in legs)
        has_acquisition = any(leg["leg_type"] == "stock_acquisition" for leg in legs)
        acquired = sum(int(leg.get("quantity") or 0) for leg in legs if leg["leg_type"] == "stock_acquisition")
        exited = sum(int(leg.get("quantity") or 0) for leg in legs if leg["leg_type"] == "stock_exit")
        status = "closed" if has_put and has_acquisition and acquired > 0 and exited == acquired else "open"
    except WheelCycleError:
        status = "requires_review"
    closed_at = None
    if status == "closed":
        exit_dates = [_text((leg.get("position") or {}).get("exit_date")) for leg in enriched if leg["leg_type"] == "stock_exit"]
        closed_at = max((date for date in exit_dates if date), default=None)
    conn.execute(
        "UPDATE strategy_cycles SET status = %s, closed_at = %s, updated_at = NOW() WHERE id = %s",
        (status, closed_at, cycle_id),
    )


def create_wheel_cycle(
    *,
    underlying: str,
    is_simulated: bool,
    opened_at: str,
    source_ref: str,
    notes: str = "",
    origin_put_position_id: int | None = None,
    conn: Any | None = None,
) -> int:
    if not _upper(underlying):
        raise WheelCycleError("Informe o ativo-base do ciclo.")
    opened = _date(opened_at, label="Data de abertura")
    reference = _text(source_ref)
    if not reference:
        raise WheelCycleError("Informe a referencia documental ou a justificativa do ciclo.")
    if conn is None:
        with db_transaction() as transaction_conn:
            return create_wheel_cycle(
                underlying=underlying,
                is_simulated=is_simulated,
                opened_at=opened,
                source_ref=reference,
                notes=notes,
                origin_put_position_id=origin_put_position_id,
                conn=transaction_conn,
            )
    ensure_wheel_cycle_schema(conn)
    result = conn.execute(
        """
        INSERT INTO strategy_cycles
            (underlying, is_simulated, opened_at, origin_put_position_id, source_ref, notes)
        VALUES (%s, %s, %s, %s, %s, %s)
        RETURNING id
        """,
        (_upper(underlying), 1 if is_simulated else 0, opened, origin_put_position_id, reference, _text(notes)),
    )
    return int(result.fetchone()["id"])


def add_wheel_cycle_leg(
    *,
    cycle_id: int,
    leg_type: str,
    position_id: int | None = None,
    quantity: int | None = None,
    amount_override: float | None = None,
    source_ref: str = "",
    notes: str = "",
    conn: Any | None = None,
) -> int:
    resolved_cycle_id = _int(cycle_id, label="ID do ciclo")
    resolved_type = _text(leg_type).lower()
    if resolved_type not in LEG_TYPES:
        raise WheelCycleError("Tipo de perna Wheel invalido.")
    reference = _text(source_ref)
    if conn is None:
        with db_transaction() as transaction_conn:
            return add_wheel_cycle_leg(
                cycle_id=resolved_cycle_id,
                leg_type=resolved_type,
                position_id=position_id,
                quantity=quantity,
                amount_override=amount_override,
                source_ref=reference,
                notes=notes,
                conn=transaction_conn,
            )
    ensure_wheel_cycle_schema(conn)
    cycle = _fetch_cycle(conn, resolved_cycle_id, lock=True)
    if resolved_type == "expense":
        if position_id is not None or quantity not in (None, 0):
            raise WheelCycleError("Despesa manual nao pode apontar para uma posicao.")
        if not reference:
            raise WheelCycleError("Despesa manual exige referencia documental.")
        amount = _money(amount_override, label="Despesa", allow_zero=False)
        if amount > 0:
            amount = -amount
        result = conn.execute(
            """
            INSERT INTO strategy_cycle_legs (cycle_id, leg_type, quantity, amount_override, source_ref, notes)
            VALUES (%s, %s, 0, %s, %s, %s) RETURNING id
            """,
            (resolved_cycle_id, resolved_type, amount, reference, _text(notes)),
        )
    else:
        resolved_position_id = _int(position_id, label="ID da posicao")
        resolved_quantity = _int(quantity, label="Quantidade")
        if amount_override is not None:
            raise WheelCycleError("Valor manual so e aceito para uma despesa documentada.")
        position = conn.execute("SELECT * FROM positions WHERE id = %s FOR UPDATE", (resolved_position_id,)).fetchone()
        if position is None:
            raise WheelCycleError("Posicao nao encontrada.")
        _validate_position_for_leg(cycle=cycle, position=position, leg_type=resolved_type, quantity=resolved_quantity)
        used = conn.execute(
            "SELECT COALESCE(SUM(quantity), 0) AS quantity FROM strategy_cycle_legs WHERE position_id = %s",
            (resolved_position_id,),
        ).fetchone()
        if int(used["quantity"] or 0) + resolved_quantity > _int(position["qty"], label="Quantidade da posicao"):
            raise WheelCycleError("A posicao ja possui quantidade alocada em outro ciclo Wheel.")
        duplicate = conn.execute(
            "SELECT 1 FROM strategy_cycle_legs WHERE cycle_id = %s AND position_id = %s",
            (resolved_cycle_id, resolved_position_id),
        ).fetchone()
        if duplicate is not None:
            raise WheelCycleError("A posicao ja pertence a este ciclo Wheel.")
        _validate_prospective_leg(
            conn,
            cycle=cycle,
            cycle_id=resolved_cycle_id,
            leg_type=resolved_type,
            position=position,
            quantity=resolved_quantity,
        )
        if resolved_type == "stock_exit":
            _validate_stock_exit_parent(
                conn, cycle_id=resolved_cycle_id, position=position, quantity=resolved_quantity
            )
        result = conn.execute(
            """
            INSERT INTO strategy_cycle_legs (cycle_id, position_id, leg_type, quantity, amount_override, source_ref, notes)
            VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING id
            """,
            (
                resolved_cycle_id,
                resolved_position_id,
                resolved_type,
                resolved_quantity,
                amount_override,
                reference,
                _text(notes),
            ),
        )
    leg_id = int(result.fetchone()["id"])
    _refresh_cycle_status(conn, resolved_cycle_id)
    return leg_id


def _ledger_value(sums: Mapping[int, Mapping[str, float]], position_id: int, key: finance.TransactionType) -> float:
    return round(float(sums.get(position_id, {}).get(key.value, 0.0)), 2)


def build_wheel_cycle_metrics(
    cycle: Mapping[str, Any],
    legs: Sequence[Mapping[str, Any]],
    *,
    positions_by_id: Mapping[int, Mapping[str, Any]],
    ledger_sums: Mapping[int, Mapping[str, float]],
) -> dict[str, Any]:
    """Calculate one explicit Wheel cycle without reusing strategy aggregate results."""

    result_before_darf = 0.0
    darf = 0.0
    acquisition_cost = 0.0
    repurchases = 0.0
    expenses = 0.0
    premiums = 0.0
    sale_value = 0.0
    detailed_legs: list[dict[str, Any]] = []
    dates: list[str] = [_text(cycle.get("opened_at"))]
    documented = 0

    enriched: list[dict[str, Any]] = []
    for leg in legs:
        item = dict(leg)
        position_id = item.get("position_id")
        position = positions_by_id.get(int(position_id)) if position_id else None
        item["position"] = position
        enriched.append(item)
        if _text(item.get("source_ref")) or (position and _position_document_ref(position)):
            documented += 1

    _validate_stock_quantities(cycle=cycle, legs=enriched)
    for leg in enriched:
        leg_type = _text(leg.get("leg_type"))
        quantity = int(leg.get("quantity") or 0)
        position = leg.get("position")
        amount = 0.0
        label = leg_type
        if leg_type == "expense":
            amount = round(float(leg.get("amount_override") or 0.0), 2)
            expenses += -amount
            label = "Despesa atribuida"
        elif position is None:
            raise WheelCycleError("Uma perna do ciclo aponta para uma posicao inexistente.")
        else:
            position_id = int(position["id"])
            total_qty = _int(position.get("qty"), label="Quantidade da posicao")
            ratio = quantity / total_qty
            dates.extend([_text(position.get("trade_date")), _text(position.get("exit_date"))])
            if leg_type in _OPTION_LEGS:
                premium = round(_ledger_value(ledger_sums, position_id, finance.TransactionType.PREMIUM) * ratio, 2)
                buyback = round(_ledger_value(ledger_sums, position_id, finance.TransactionType.BUY) * ratio, 2)
                amount = round(premium + buyback, 2)
                premiums += premium
                repurchases += max(-buyback, 0.0)
                label = "PUT de origem" if leg_type == "put_origin" else "CALL coberta"
            elif leg_type == "stock_acquisition":
                base = round((float(position.get("entry_price") or 0.0) * quantity) + (float(position.get("fees") or 0.0) * ratio), 2)
                amount = -base
                acquisition_cost += base
                label = "Aquisicao das acoes"
            elif leg_type == "stock_exit":
                gross = float(position.get("exit_price") or 0.0) * quantity
                fee = float(position.get("fees") or 0.0) * ratio
                amount = round(gross - fee, 2)
                sale_value += amount
                label = "Saida das acoes"
            else:
                raise WheelCycleError("Tipo de perna Wheel nao reconhecido.")
            darf += round(_ledger_value(ledger_sums, position_id, finance.TransactionType.DARF) * ratio, 2)
        result_before_darf = round(result_before_darf + amount, 2)
        detailed_legs.append(
            {
                "id": leg.get("id"),
                "leg_type": leg_type,
                "label": label,
                "position_id": leg.get("position_id"),
                "ticker": position.get("ticker") if position else None,
                "quantity": quantity or None,
                "amount": amount,
                "source_ref": _text(leg.get("source_ref")) or (_position_document_ref(position) if position else ""),
            }
        )

    valid_dates = []
    for value in dates:
        try:
            valid_dates.append(dt.date.fromisoformat(value))
        except ValueError:
            continue
    start = min(valid_dates) if valid_dates else None
    end = max(valid_dates) if valid_dates else None
    duration = max((end - start).days, 1) if start and end else None
    capital_max = round(acquisition_cost + repurchases + expenses, 2)
    capital_consumed = capital_max
    return_pct = round((result_before_darf / capital_max) * 100.0, 4) if capital_max > 0 else None
    coverage_pct = round((documented / len(enriched)) * 100.0, 2) if enriched else 0.0
    return {
        "id": cycle.get("id"),
        "underlying": cycle.get("underlying"),
        "is_simulated": bool(cycle.get("is_simulated") or 0),
        "status": cycle.get("status"),
        "opened_at": cycle.get("opened_at"),
        "closed_at": cycle.get("closed_at"),
        "source_ref": cycle.get("source_ref"),
        "notes": cycle.get("notes"),
        "result_before_darf": result_before_darf,
        "official_darf": round(darf, 2),
        "capital_max": capital_max,
        "capital_consumed": capital_consumed,
        "return_pct": return_pct,
        "duration_days": duration,
        "coverage_pct": coverage_pct,
        "documented_legs": documented,
        "legs": detailed_legs,
        "premiums": round(premiums, 2),
        "sale_value": round(sale_value, 2),
        "acquisition_cost": round(acquisition_cost, 2),
        "repurchases": round(repurchases, 2),
        "expenses": round(expenses, 2),
    }


def list_wheel_cycles(*, is_simulated: bool) -> list[dict[str, Any]]:
    with db_transaction() as conn:
        ensure_wheel_cycle_schema(conn)
        rows = conn.execute(
            "SELECT * FROM strategy_cycles WHERE is_simulated = %s ORDER BY opened_at DESC, id DESC",
            (1 if is_simulated else 0,),
        ).fetchall()
        cycles = [dict(row) for row in rows]
        cycle_legs = {int(cycle["id"]): _fetch_cycle_legs(conn, int(cycle["id"])) for cycle in cycles}
    position_ids = {int(leg["position_id"]) for legs in cycle_legs.values() for leg in legs if leg.get("position_id")}
    positions = {int(position["id"]): position for position in list_positions(include_closed=True) if int(position["id"]) in position_ids}
    ledger_sums = finance.get_ledger_sums_by_position(
        types=[finance.TransactionType.PREMIUM, finance.TransactionType.BUY, finance.TransactionType.DARF],
        is_simulated=is_simulated,
    )
    metrics: list[dict[str, Any]] = []
    for cycle in cycles:
        try:
            metrics.append(build_wheel_cycle_metrics(cycle, cycle_legs[int(cycle["id"])], positions_by_id=positions, ledger_sums=ledger_sums))
        except WheelCycleError as exc:
            metrics.append({**cycle, "status": "requires_review", "error": str(exc), "legs": []})
    return metrics


def build_wheel_backfill_plan(positions: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]:
    """Find only parent-linked histories whose Wheel chain is unequivocal."""

    by_parent: dict[int, list[Mapping[str, Any]]] = defaultdict(list)
    for position in positions:
        try:
            parent = int(position.get("parent_position_id") or 0)
        except (TypeError, ValueError):
            parent = 0
        if parent:
            by_parent[parent].append(position)
    plan: list[dict[str, Any]] = []
    for put in positions:
        put_id = int(put.get("id") or 0)
        if not put_id or _text(put.get("strategy_tag")).lower() != "cash_put":
            continue
        if infer_option_type(put.get("ticker")) != "PUT" or not _is_exercise(put.get("exit_reason")):
            continue
        stock_candidates = [
            item for item in by_parent.get(put_id, [])
            if infer_option_type(item.get("ticker")) is None and _upper(item.get("ticker")) == _upper(put.get("underlying"))
            and bool(item.get("is_simulated") or 0) == bool(put.get("is_simulated") or 0)
        ]
        if len(stock_candidates) != 1:
            plan.append({"put_position_id": put_id, "status": "requires_review", "reason": "PUT exercida sem uma unica aquisicao de acoes vinculada."})
            continue
        stock = stock_candidates[0]
        calls = [
            item for item in by_parent.get(int(stock["id"]), [])
            if _text(item.get("strategy_tag")).lower() == "covered_call" and infer_option_type(item.get("ticker")) == "CALL"
            and bool(item.get("is_simulated") or 0) == bool(put.get("is_simulated") or 0)
        ]
        calls.sort(key=lambda item: (_text(item.get("trade_date")), int(item.get("id") or 0)))
        if not calls:
            plan.append({"put_position_id": put_id, "status": "requires_review", "reason": "Aquisicao sem CALL vinculada; ciclo permanece sem confirmacao."})
            continue
        exits: list[Mapping[str, Any]] = []
        problems: list[str] = []
        for call in calls:
            if not _is_exercise(call.get("exit_reason")):
                continue
            matching = [
                item for item in by_parent.get(int(call["id"]), [])
                if infer_option_type(item.get("ticker")) is None and _upper(item.get("ticker")) == _upper(put.get("underlying"))
                and _text(item.get("exit_date")) == _text(call.get("exit_date"))
                and int(item.get("qty") or 0) == int(call.get("qty") or 0)
            ]
            if len(matching) != 1:
                problems.append(f"CALL #{call['id']} exercida sem uma unica saida de acoes correspondente.")
            else:
                exits.extend(matching)
        if problems:
            plan.append({"put_position_id": put_id, "status": "requires_review", "reason": " ".join(problems)})
            continue
        stock_qty = int(stock.get("qty") or 0)
        if sum(int(item.get("qty") or 0) for item in exits) > stock_qty:
            plan.append({"put_position_id": put_id, "status": "requires_review", "reason": "As saidas vinculadas ultrapassam o lote adquirido."})
            continue
        exits.sort(key=lambda item: (_text(item.get("exit_date")), int(item.get("id") or 0)))
        plan.append(
            {
                "put_position_id": put_id,
                "status": "ready",
                "underlying": _upper(put.get("underlying")),
                "is_simulated": bool(put.get("is_simulated") or 0),
                "opened_at": _text(put.get("trade_date")),
                "position_legs": [
                    (put, "put_origin"),
                    (stock, "stock_acquisition"),
                    *[(call, "covered_call") for call in calls],
                    *[(item, "stock_exit") for item in exits],
                ],
            }
        )
    return plan


def backfill_wheel_cycles(*, apply: bool = False) -> dict[str, Any]:
    positions = list_positions(include_closed=True)
    plan = build_wheel_backfill_plan(positions)
    report = {"applied": False, "created_cycle_ids": [], "ready": [], "requires_review": []}
    with db_transaction() as conn:
        ensure_wheel_cycle_schema(conn)
        existing = {
            int(row["origin_put_position_id"])
            for row in conn.execute("SELECT origin_put_position_id FROM strategy_cycles WHERE origin_put_position_id IS NOT NULL").fetchall()
        }
        for item in plan:
            if item["status"] != "ready":
                report["requires_review"].append(item)
                continue
            put_id = int(item["put_position_id"])
            if put_id in existing:
                report["ready"].append({**item, "status": "already_exists"})
                continue
            report["ready"].append(item)
            if not apply:
                continue
            cycle_id = create_wheel_cycle(
                underlying=item["underlying"],
                is_simulated=item["is_simulated"],
                opened_at=item["opened_at"],
                origin_put_position_id=put_id,
                source_ref=(
                    f"Backfill auditavel da PUT #{put_id}: vinculos legados conferidos por ativo, modo, "
                    "quantidade e cronologia; confirme as referencias documentais das pernas sem nota registrada."
                ),
                conn=conn,
            )
            for position, leg_type in item["position_legs"]:
                add_wheel_cycle_leg(
                    cycle_id=cycle_id,
                    leg_type=leg_type,
                    position_id=int(position["id"]),
                    quantity=int(position["qty"]),
                    conn=conn,
                )
            report["created_cycle_ids"].append(cycle_id)
        report["applied"] = bool(apply and report["created_cycle_ids"])
    return report


__all__ = [
    "LEG_TYPES",
    "WheelCycleError",
    "add_wheel_cycle_leg",
    "backfill_wheel_cycles",
    "build_wheel_backfill_plan",
    "build_wheel_cycle_metrics",
    "create_wheel_cycle",
    "ensure_wheel_cycle_schema",
    "list_wheel_cycles",
]
